<!-- Start content  -->

<div class="content">
	<article class="col-3">
		<div class="col_title">Conditions d'utilisation de Edinars</div>
		<div class="col_text">
			<p class="p1">Voici les termes et conditions applicables lorsque vous consentez à utiliser nos services</p>

							<p class="pTitle">1. A propos de Edinars </p>
								<p class="p1">1.1. Sarl Edinars est une société constituée en vertu des lois de la République Algérienne Démocratique et Populaire portant le numéro de matricule fiscale . Inscrit au Registre de Commerce sous le n°: , dont le siège est sis à: </p>
							<p class="pTitle">2. Portée des présentes conditions d'utilisation</p>
								<p class="p1">2.1. Les présentes conditions d'utilisation régissent l'ouverture, l’utilisation et la clôture de votre compte Edinars. En même temps que notre Politique en matière de protection de la vie privée, elles constituent le lien légal entre vous et nous. Pour l'usage des services complémentaires, il se peut que vous deviez accepter des conditions générales additionnelles, comme vous y êtes invités lorsque vous commandez ou utilisez de tels services. Il vous est conseillé d'imprimer ou de télécharger une copie des présentes conditions d'utilisation et de la conserver pour référence ultérieure. Vous pouvez toujours consulter les dernières conditions d'utilisation sur notre site.</p>
								<p class="p1">2.2. Il vous est également conseillé de lire les réponses aux questions fréquemment posées sur notre site.</p>
								<p class="p1">2.3. Selon le type de compte que vous avez, des conditions générales additionnelles peuvent s'appliquer comme cela vous sera communiqué au moment opportun.</p>
							<p class="pTitle">3. Votre compte Edinars</p>
								<p class="p1">3.1. Votre compte Edinars est un compte de gestion de vos opérations de paiement électronique, qui vous permet d'envoyer et de recevoir des paiements électroniques.</p>
								<p class="p1">3.2. L'argent sur votre compte est un prépaiement sur vos prochaines opérations, vous donne autorisation à la Sarl Edinars à payer les fournisseurs ou les prestataires conventionnés à votre place en utilisant votre solde, qu'est toujours visible dans votre compte.</p>
								<p class="p1">3.3. Votre compte Edinars est exprimé dans la devise nationale DZD (Dinar Algérien). Et votre compte est valable uniquement pour payer des fournisseurs ou prestataires installés en Algérie.</p>
								<p class="p1">3.4. L'argent contenu sur votre compte Edinars ne perd jamais sa valeur mais il ne rapportera aucun intérêt.</p>
<p class="p1">3.5. Vous avez le droit de retirer votre argent de votre compte Edinars à tout moment ; cependant, il peut vous être demandé de confirmer votre identité au préalable. Il n'y a aucun montant de retrait minimum mais les fonds sur votre compte doivent être suffisants pour couvrir tout éventuel frais de retrait applicable. Vous pouvez choisir la méthode de retrait en soumettant votre demande de retrait.</p>
<p class="p1">3.6. Les comptes Edinars ne sont pas des comptes bancaires. En acceptant les présentes conditions d’utilisation, vous reconnaissez que les Autorités Financières Algériennes ne s’appliquent pas à votre compte Edinars. Dans le cas peu probable où SARL Edinars devenait insolvable, vous pourriez perdre l'argent placé sur votre compte. Cependant, SARL Edinars respecte rigoureusement les exigences légales prescrites par les autorités pour assurer la sécurité et la liquidité des fonds déposés sur des comptes Edinars. Pour de plus amples informations sur la façon dont nous préservons la sécurité des fonds de nos clients, veuillez consulter notre site Internet.</p>
<p class="p1">3.7. L'argent placé sur un compte Edinars appartient à la personne ou à la personne morale qui est enregistrée en tant que détenteur du compte. Aucune autre personne que le détenteur du compte n'a de droit sur les fonds placés sur un compte Edinars, excepté dans les cas de succession. Vous ne pouvez pas attribuer ou transférer votre compte Edinars à un tiers ni accorder un intérêt légal ou équitable sur celui-ci à un tiers.</p>
<p class="p1">3.8. Votre compte Edinars peut être sujet à des limites de dépôt, de paiement et de retrait, selon votre statut de vérification de votre compte Edinars.</p>
<p class="pTitle">4. Ouverture de votre compte</p>
<p class="p1">4.1. Afin d’utiliser les services de paiement Edinars, vous devez d'abord ouvrir un compte Edinars en enregistrant vos coordonnées sur notre site www.Edinars. En tant qu'élément du processus d'inscription, vous devrez accepter ces limites d'utilisation ainsi que notre politique en matière de protection de la vie privée. Si vous commandez des services complémentaires, vous pouvez être invité à accepter des conditions générales additionnelles. Il vous est recommandé d’imprimer et de conserver une copie des présentes conditions d'utilisation pour référence ultérieure.</p>
<p class="p1">4.2. Vous devez être âgé d’au moins 18 ans pour utiliser nos services et, en ouvrant un compte Edinars, vous déclarez que vous êtes âgé d’au moins 18 ans. Cela ne s'applique pas aux produits pour lesquels nous fixons une limite d'âge différente. Nous pouvons vous demander à tout moment de prouver votre âge.</p>
<p class="p1">4.3. Vous ne pouvez ouvrir qu'un compte Edinars à moins que nous approuvions explicitement l'ouverture de comptes supplémentaires.</p>
<p class="p1">4.4. Vous ne pouvez ouvrir un compte Edinars que si cela est légal dans votre pays de résidence. En ouvrant un compte, vous indiquez et vous nous garantissez qu’en ouvrant un compte, vous ne violez aucunes des lois ni aucun des règlements qui vous sont applicables. Vous nous indemniserez contre toutes les pertes que nous encourrons à la suite de toute infraction à cette section de votre part.</p>
<p class="p1">4.5. Toutes les informations que vous fournissez lors du processus d'inscription ou n'importe quand par la suite doivent être précises et véridiques.</p>
<p class="p1">4.6. Vous ne pouvez ajouter des instruments de paiement (tels que des comptes bancaires, des cartes de crédit ou des cartes de débit) à votre compte Edinars que si vous êtes le détenteur désigné de cet instrument de paiement. Nous prenons toute violation de cette condition très au sérieux et traiterons n'importe quelle tentative d'ajout d’un instrument de paiement dont vous n'êtes pas le détenteur désigné comme un acte frauduleux.</p>
<p class="p1">4.7. Pendant l'inscription, il vous sera demandé si vous avez l'intention d'utiliser votre compte Edinars à des fins privées ou commerciales. Si vous avez l’intention d'utiliser votre compte à des fins commerciales, vous devez nous le dire, même si vous l'utilisez également à des fins privées. Si vous avez déclaré que vous utiliserez votre compte à des fins privées uniquement, vous devez nous dire si, à un moment quelconque dans le futur, vous l'utiliserez à des fins commerciales en contactant le service clientèle. Vous utilisez votre compte à des fins commerciales si vous recevez des paiements pour ou concernant une activité économique quelconque. Nous nous réservons le droit de déterminer si, à notre avis raisonnable, vous utilisez votre compte à des fins commerciales. Si vous utilisez votre compte à des fins commerciales, en plus des présentes conditions d'utilisation, vous serez lié par nos conditions générales pour marchands (disponibles sur https://www.Edinars/docs/merchantstos/) et vous payerez des frais tels qu'indiqués sur notre page de tarifs marchands (disponibles sur http://www.Edinars/docs/merchantfees/). Si vous n'arrivez pas à déterminer si une activité s’apparente à une activité commerciale, vous devez entrer en contact avec le service clientèle.</p>
<p class="p1">4.8. Dans les quinze jours de la date d'ouverture de votre compte Edinars, vous pouvez clôturer votre compte gratuitement en contactant le service clientèle ; cependant, si vous avez verser des fonds sur votre compte Edinars, vous pouvez être tenu de fournir des documents d'identité avant de pouvoir retirer des fonds. Les transactions et les frais pour des transactions effectuées avant que vous ne clôturiez votre compte (y compris les transactions qui ne sont pas révocables et qui ont été lancées mais pas achevées avant la fermeture de compte) ne seront pas remboursés.</p>
 <p class="pTitle">5. Gestion de votre compte</p>
<p class="p1">5.1. Vous devez vous assurer que les informations enregistrées sur votre compte Edinars sont toujours précises et à jour et nous ne serons tenus pour responsables d'aucune perte si vous ne le faites pas. Nous pouvons vous demander à tout moment de confirmer l'exactitude de vos informations ou de fournir des documents ou toute autre preuve.</p>
<p class="p1">5.2. Nous pouvons vous contacter par e-mail ou de diverses autres manières comme nous le décrivons dans la section 19 d’informations ou dans les notifications concernant votre compte Edinars. Il est de votre responsabilité de vérifier régulièrement le bon fonctionnement de votre compte e-mail ou des autres méthodes de communication que vous avez enregistrées dans votre compte et de récupérer et de lire promptement les messages concernant votre compte. Nous ne serons responsables d'aucune perte si vous ne le faites pas.</p>
<p class="p1">5.3. Les chargement de crédit, les paiements reçus, les paiements envoyés et les retraits de crédit sont indiqués dans votre historique de transactions en ligne avec les frais imputés. Un code unique d'identification de transaction est attribué à chaque transaction et est affiché dans l'historique des transactions. Vous devez mentionner ce code d'identification de transaction pour toute communication avec nous au sujet d'une transaction particulière. Vous devez vérifier l’historique du solde et des transactions de votre compte régulièrement. </p>
Vous devez signaler toutes les irrégularités ou clarifier toutes les questions que vous pourriez avoir dès que possible en contactant le service clientèle.</p>
<p class="pTitle">6. Maintien de la sécurité de votre compte Edinars</p>
<p class="p1">6.1. Vous devez préserver la sécurité du mot de passe de votre compte à tout moment et ne jamais le révéler à qui que ce soit. Notre personnel ne vous demandera jamais de lui fournir votre mot de passe ou de le donner à un tiers. Tout message que vous recevez ou tout site que vous consultez vous demandant votre mot de passe, en dehors du site d’Edinars ou d’une passerelle de paiement Edinars sur le site d’un négociant, doit nous être signalé. Si vous doutez de l’authenticité d’un site, vous devez contacter le service clientèle. Vous devez changer votre mot de passe régulièrement et vous ne devez jamais :
<br>•	Noter ou stocker votre mot de passe où que ce soit ;
<BR>•	Autoriser quelqu'un à accéder à votre compte ou à vous regarder accéder à votre compte ;
<br>•	Choisir un mot de passe qui est peut-être facilement deviné par quelqu'un qui pourrait utiliser ou recueillir des informations sur vous; ou
<br>•	Choisir un mot de passe qui a un sens.</p>
<p class="p1">6.2. Si vous avez des signes ou soupçons concernant la perte, le vol, le détournement, l’utilisation non autorisée voire la divulgation de votre login, de votre mot de passe ou de tout autre dispositif de sécurité, vous devez changer votre mot de passe et contacter le service clientèle immédiatement. Si vous tardez de manière injustifiée à nous en informer, cela peut non seulement compromettre la sécurité de votre compte mais vous pourriez également être tenu pour responsable de toutes les pertes qui en résultent. Si vous suspectez que quelqu'un d'autre a accédé à votre compte, vous devez également contacter la police et signaler l'incident.</p>
<p class="p1">6.3. Nous pouvons à tout moment suspendre ou bien limiter la fonctionnalité de votre compte si nous suspectons qu'on y a accédé sans votre autorisation ou qu'il a été compromis de quelque manière que ce soit.</p>
<p class="p1">6.4. Vous devez également faire tout ce qui est raisonnablement nécessaire pour vous assurer que vos comptes e-mail sont sécurisés et que vous seul y accédez, car il se peut que votre adresse e-mail soit utilisée pour réinitialiser des mots de passe ou pour communiquer avec vous au sujet de la sécurité de votre compte. Au cas où l'unes des adresses e-mails enregistrées dans votre compte Edinars serait compromise, vous devez immédiatement contacter le service clientèle ainsi que votre fournisseur de services e-mail.</p>
<p class="p1">6.5. Si vous utilisez un ordinateur public ou partagé pour accéder à votre compte Edinars, vous devez vous assurer que vos coordonnées de connexion ne sont pas stockées par le navigateur, mises en cache ou enregistrées de quelque manière que ce soit. Si vous utilisez votre propre ordinateur, vous devez vous assurer que vous seul y avez accès. Vous ne devez jamais utiliser de fonctionnalité qui permette le stockage de coordonnées de connexion ou de mots de passe par l'ordinateur que vous utilisez.</p>
<p class="p1">6.6. Les produits ou les services additionnels que vous utilisez peuvent impliquer des exigences de sécurité supplémentaires et vous devez vous familiariser avec celles-ci comme cela vous sera notifié.</p>
<p class="pTitle">7. Clôture de votre compte</p>
<p class="p1">7.1. Vous pouvez clôturer votre compte Edinars à tout moment en contactant le service clientèle.</p>
<p class="p1">7.2. Si votre compte contient un solde au moment de sa clôture, nous vous demanderons de retirer vos fonds dans un délai raisonnable au cours duquel votre compte sera accessible pour vous permettre de retirer le solde restant uniquement. Votre engagement à préserver la sécurité de votre compte comme stipulé dans la section 6 continuera à être d’application. Si vous ne retirez pas les fonds dans le délai fixé, nous pouvons (sans y être obligés) vous envoyer un chèque à l'adresse enregistrée dans le profil de votre compte Edinars et vous facturerons les frais applicables aux retraits par chèque (y compris les frais d'émission et d'envoi de chèque). Il est de votre responsabilité de maintenir votre adresse à jour et nous ne serons responsables d'aucune perte résultant de votre manquement à celle-ci.</p>
<p class="p1">7.3. La clôture de votre compte ne fait pas disparaître les données personnelles que nous détenons sur vous et nous continuerons à stocker de telles données, y compris l'historique de transactions, pendant une période minimum de cinq ans comme l’exige la loi.</p>
<p class="pTitle">8. Dépôt de fonds</p>
<p class="p1">8.1. Vous pouvez déposer (charger) des fonds en visitant le site www.Edinars, en vous connectant à votre compte et en suivant les instructions de chargement appropriées. Un certain nombre de méthodes de chargement différentes peuvent vous être présentées, en fonction des instruments de paiement que vous avez ajoutés à votre compte Edinars et des méthodes de paiement disponibles dans votre pays de résidence. Les méthodes de chargement sont des services de paiement fournis par des institutions financières tierces (par exemple, l'émetteur de la carte de paiement que vous utilisez pour charger des fonds ou des prestataires de service d'opérations bancaires directes tiers) et ne font pas partie du service Edinars. Edinars ne garantit l'utilisation d'aucune méthode de chargement particulière et peut rendre disponible, modifier ou cesser l'acceptation de toute méthode de chargement particulière à tout moment sans suivre la procédure présentée dans la clause 18. Edinars ne sera pas responsable du paiement chargé jusqu'à ce que les fonds chargés soient reçus par Edinars Sarl.</p>
<p class="p1">8.2. Vous pouvez être invité à répondre à des questions de sécurité ou à accomplir d'autres activités que nous pouvons raisonnablement exiger pour assurer l'autorisation appropriée d'une transaction à chargement.</p>
<p class="p1">8.3. Si vous choisissez une méthode de chargement utilisant un instrument de paiement qui peut être sujet à des droits de chargeback comme, entre autres, une carte de crédit ou de débit ou le débit direct, vous déclarez que vous n'exercerez pas ces droits de chargeback pour autre chose que l'usage non autorisé de l'instrument de paiement ou pour une infraction de Edinars aux présentes conditions d'utilisation qui aurait pour conséquence que vous ayez droit au remboursement du montant chargé. Vous ne pouvez appliquer de chargeback à une transaction à chargement ou autoriser le chargeback d’une transaction à chargement pour des raisons qui n’engage pas la responsabilité de SARL Edinars comme, entre autres, des litiges avec des négociants pour la non-livraison de biens ou de services ou un solde insuffisant sur le compte de l'instrument de paiement. Nous nous réservons le droit de vous facturer des frais et des dépenses que nous encourons à la suite d’un tel chargeback et de toute action entreprise pour contester celui-ci. Nous pouvons également vous facturer des frais de chargeback de 1000 DA.</p>
<p class="p1">8.4. Vous pouvez permettre à un marchand que vous souhaitez payer au moyen d’Edinars de façon régulière (par exemple, pour un service d'abonnement) de débiter votre compte Edinars pour chaque paiement périodique. Dans ce cas, vous autorisez Edinars à débiter l'instrument de paiement (par exemple, votre carte de crédit ou votre compte bancaire) que vous avez utilisé pour effectuer le paiement original également pour tous les paiements suivants. Vous acceptez de ne pas supprimer ni annuler de telles transactions périodiques simplement en contactant l'émetteur de l'instrument de paiement (par exemple, votre fournisseur de carte de crédit ou votre banque). Afin d'annuler les paiements périodiques à l'avenir, vous devez (a) contacter Edinars et (b) informer le négociant dont vous avez acheté les biens ou les services que vous avez annulé le paiement périodique. Vous pouvez également nous demander de rembourser tout paiement périodique passé à condition que (a) l'autorisation initiale donnée à nous ou au négociant ne spécifiait pas le montant exact du paiement et (b) que le montant du paiement dépassait la somme à laquelle vous pouviez raisonnablement vous attendre en considération de votre modèle de dépense précédent et des circonstances du cas. Vous devez demander un tel remboursement dans un délai de quatre semaines à partir de la date à laquelle les fonds ont été débités de votre compte Edinars.</p>
<p class="p1">8.5. Si le chargeback ou l’inversion du chargement d’une transaction a pour conséquence un solde négatif sur votre compte, vous serez prié de rembourser ce solde négatif en chargeant des fonds suffisants sur votre compte. Le manquement à cette demande est une infraction aux présentes conditions d'utilisation. Le remboursement du solde négatif est dû immédiatement sans communication préalable ; cependant, nous nous réservons le droit, à tout moment, de vous envoyer des rappels ou de prendre d'autres mesures de recouvrement de dettes, y compris, entres autres, de mandater une agence de recouvrement de dettes ou des avocats-conseils ou de réclamer une indemnisation devant le tribunal. Nous nous réservons le droit de vous facturer les dépenses que nous encourons raisonnablement en entreprenant des démarches de recouvrement de dettes ou des mesures contraignantes.</p>
<p class="p1">8.6. Les fonds chargés seront crédités sur votre compte Edinars le jour même où les fonds sont reçus par SARL Edinars. Centaines transactions à téléchargement, par exemple au moyen d’une carte de crédit ou de débit, par débit direct ou via des opérations bancaires directes, seront créditées sur votre compte immédiatement, mais sont sujettes à annulation au cas où les fonds réels n'atteindraient pas Edinars dans un délai raisonnable, auquel cas SARL Edinars déduira cette transaction annulée du solde de votre compte Edinars. Si le solde de votre compte est insuffisant, nous nous réservons le droit d'exiger un remboursement de votre part.</p>
<p class="p1">8.7. Dans le cadre d'une transaction à chargement au moyen d’un instrument de paiement, Edinars est un receveur de paiement et non un fournisseur de services de paiement.</p>
</p><p class="p1">8.9. Les chargements peuvent être sujets à des limites de chargement pour des raisons de sécurité et d’exigences légales. Ces limites sont fixées dynamiquement selon votre statut de vérification et la méthode de chargement que vous voulez utiliser. Vous devez garder à l’esprit que, selon votre statut de vérification, vos limites de chargement peuvent être supérieures à vos limites de retrait ou de dépense. Vous pouvez consulter ces limites à tout moment dans la section correspondante du profil de votre compte.</p>
</p><p class="p1">8.10. Les chargements sont sujets à des frais de chargement et de conversion de devise en fonction de l'instrument de paiement et de la méthode de chargement choisis. Veuillez consulter la section 14 pour de plus amples détails.</p>
</p><p class="pTitle">9. Envoi de paiements
</p><p class="p1">9.1. Pour envoyer à un paiement, vous devez d’abord autoriser le paiement avec votre login et votre mot de passe. Nous pouvons également vous poser des questions de sécurité complémentaires en rapport avec vous ou votre compte. Si votre compte est protégé par des mesures de sécurité supplémentaires telles que l'utilisation de tokens de mot de passe, vous devez suivre les instructions qui vous ont été fournies en même temps que ces mesures de sécurité supplémentaires. Si votre compte est autorisé à effectuer des paiements en masse, la procédure pour effectuer de tels paiements vous sera communiquée dans le manuel d'intégration approprié.
</p><p class="p1">9.2. Chaque bénéficiaire d'un paiement que vous souhaitez envoyer via Edinars doit avoir une adresse e-mail valable.
</p><p class="p1">9.3. Si vous êtes invité à fournir l'adresse e-mail du bénéficiaire, vous devez faire très attention à taper correctement l'adresse e-mail exacte à laquelle vous souhaitez envoyer l'argent. Edinars utilise l'adresse e-mail comme identifiant unique pour déterminer le bénéficiaire prévu du paiement que vous nous demandez de traiter. Toutes les autres informations que vous fournirez en plus de l'adresse e-mail du bénéficiaire sont susceptibles de ne pas être prises en compte sauf l'identifiant de compte Edinars, et nous ne serons pas responsables des erreurs que vous pourriez faire en saisissant l'adresse e-mail du bénéficiaire.
</p><p class="p1">9.4. Si l'adresse e-mail du bénéficiaire prévu est enregistrée dans Edinars, les fonds seront immédiatement crédités au compte Edinars lié à cette adresse e-mail, à moins que vous utilisiez le service de dépôt fiduciaire de Edinars comme décrit dans la section 13. Une fois que les fonds sont crédités au compte du bénéficiaire, la transaction devient irréversible.
</p><p class="p1">9.5. Si l'adresse e-mail du bénéficiaire n'est pas enregistrée dans Edinars, nous enverrons un e-mail de notification à cette adresse e-mail avec des instructions sur la manière de réclamer et de recevoir le paiement. Si le bénéficiaire ne réclame pas le paiement dans les quinze jours, les fonds vous seront restitués. Vous pouvez également annuler la transaction à tout moment si les fonds n'ont pas encore été crédités sur le compte Edinars du bénéficiaire. Pour annuler une transaction, vous devez vous connecter à votre compte Edinars, localiser la transaction appropriée dans votre historique de transactions et choisir « Annuler ».
</p><p class="p1">9.6. Vous pouvez effectuer des paiements périodiques en créant un ordre permanent sur votre compte. Vous pouvez annuler votre demande de paiement périodique pour des paiements futurs à tout moment en vous connectant à votre compte et en le supprimant. Vous ne pourrez pas annuler les transactions qui ont été déjà créditées au bénéficiaire.
</p><p class="p1">9.7. Les paiements sont sujets à des limites de paiement pour des raisons de sécurité et d’exigences légales. Ces limites sont fixées dynamiquement selon votre statut de vérification. Vous pouvez consulter ces limites à tout moment dans le profil de votre compte. Vous devez vous assurer que vos limites sont suffisantes pour couvrir le paiement que vous avez l'intention d'effectuer ainsi que tous les frais applicables, dont les frais de prestations de service et de conversion de devise. Vous devez garder à l’esprit que le bénéficiaire d'un paiement peut également être sujet à des limites de dépense et de retrait et que cela peut influencer l'accès du bénéficiaire aux fonds que vous prévoyez de lui envoyer.
</p><p class="p1">9.8. L'envoi des paiements est sujet à des frais et à des coûts de conversion de devise en fonction du type de paiement que vous effectuez et du type de compte que vous avez. Veuillez consulter la section 14 pour de plus amples détails.
</p><p class="pTitle">10. Réception de fonds
</p><p class="p1">10.1. Si vous recevez des fonds sur votre compte Edinars, nous vous enverrons un e-mail de notification et afficherons le paiement comme transaction de réception d'argent dans votre historique de transactions. Vous devez régulièrement établir une correspondance entre les paiements entrants et vos propres archives.
</p><p class="p1">10.2. La confirmation de réception de paiements sur votre compte ne signifie pas nécessairement que ces transactions ne sont pas annulables. Edinars se réserve le droit d'annuler un paiement au cas où le débiteur ou la banque du débiteur ou le fournisseur de services de paiement a rétro facturé ou annulé (ou est vraisemblablement susceptible de rétro facturer ou d'annuler) un chargement ou tout autre paiement qui a été utilisé pour vous verser le paiement.
</p><p class="p1">10.3. Si une personne reçoit une notification de paiement d’Edinars indiquant que quelqu'un lui a envoyé des fonds à une adresse e-mail qui n'est pas enregistrée, elle ne sera pas créditée du paiement jusqu'à ce qu'elle le réclame selon les instructions présentées dans l'e-mail de notification. Dans le cas contraire, il n'y aura aucun lien contractuel ni fiduciaire entre Edinars et le bénéficiaire prévu. Les fonds restent ceux de l'expéditeur.
</p><p class="p1">10.4. Vous pouvez réclamer un paiement à quelqu'un en utilisant le service de « Demande de paiement » de votre compte. Vous ne devez utiliser ce service que pour des montants incontestés qui sont dus en intégralité par une personne. Vous ne pouvez pas utiliser ce service plus d'une fois pour le même paiement que vous réclamez. Ce service ne peut être utilisé comme outil de recouvrement de dettes ou de mesure contraignante. Si la personne qui vous doit un paiement vous demande de ne pas utiliser le service de « Demande de paiement » de Edinars pour lui réclamer le paiement, vous devez vous conformer à cette demande indépendamment du bien-fondé de votre réclamation. En utilisant ce service, vous devez vous assurer que vous avez le droit de contacter la personne à laquelle vous réclamez l'argent. Il vous est strictement interdit de réclamer de l'argent à quelqu'un qui
<br>•	ne vous doit pas le montant demandé ;
<br>•	serait inéligible pour ouvrir un compte Edinars (par exemple, un mineur) ; ou
<br>•	n'a pas donné ou a retiré son consentement pour recevoir une demande de paiement par l'intermédiaire du service de «Demande de paiement»;
<br> Et nous auront le droit de réclamer une compensation pour tous les dommages ou pertes consécutifs à votre violation de cette interdiction.
</p><p class="p1">10.5. La réception des paiements est sujette à des frais divers et à des conversions de devise en fonction du type de paiement que vous recevez et du type de compte que vous avez. Veuillez consulter la section 14 pour de plus amples détails.
</p><p class="pTitle">11. Transactions interdites
</p><p class="p1">11.1. Il est strictement interdit d'envoyer ou de recevoir des paiements en compensation de la vente ou de la fourniture des articles suivants :
<br>•	Produits de tabac
<br>•	Médicaments sous prescription
<br>•	Drogues et attirails associés à la consommation de drogues
<br>•	Armes à feu ou munitions
<br>•	Armes et couteaux
<br>•	Désembrouiller de télévision par satellite et par câble
<br>•	Pornographie
<br>•	Identifications et licences gouvernementales comprenant les reproductions et les originaux
<br>•	Loteries ou services de jeu non autorisés
<br>•	Cartes de débit prépayées ou autres cartes à valeur intégrée qui ne sont pas associées à un négociant particulier et ne sont pas limitées aux achats de produits ou de services particuliers
<br>•	Marketing à plusieurs niveaux, vente pyramidale ou chaîne de Ponzi, programmes matrices ou autre promotion du style « Devenez riche rapidement » ou plans d'investissement à rendement élevé
<br>•	Biens ou services qui violent les droits de propriété intellectuelle d'un tiers.
<br>
Edinars se réserve le droit d'ajouter, à sa seule discrétion, des catégories commerciales de transactions interdites en ajoutant de telles catégories aux présentes conditions d'utilisation ou à une politique d'utilisation acceptable publiée sur le site.
</p><p class="p1">11.2. Il est strictement interdit d'effectuer ou de recevoir des paiements en faveur ou provenant de personnes ou d'entités offrant des services de jeu, dont, entre autres, des paris sportifs, des jeux de casino et des parties de poker illégaux. Nous pouvons suspendre ou clôturer votre compte Edinars à tout moment ou refuser d'exécuter ou annuler une transaction si nous croyons que vous utilisez ou avons utilisé directement ou indirectement votre compte Edinars pour des transactions de jeu illégales ou en rapport avec celles-ci. Il est de votre responsabilité de vous assurer que vous n'utilisez pas nos services pour des transactions qui peuvent être considérées comme illégales dans votre juridiction.
</p><p class="p1">11.3. Vous ne pouvez pas utiliser les services Edinars si vous résidez dans l'un des pays suivants: Afghanistan, Cuba, Iran, Israël, Birmanie, Nigéria, Corée du Nord, Somalie, Soudan ou Yémen. Cette liste n'est pas exhaustive et nous pouvons, à notre seule discrétion, décider de cesser ou de limiter nos services dans d'autres pays à tout moment et sans préavis. Nous nous réservons le droit de suspendre ou de clôturer votre compte Edinars à tout moment si nous estimons raisonnablement que la loi nous y oblige ou afin de nous conformer aux recommandations émises par une autorité gouvernementale compétente ou un corps reconnu pour la prévention des crimes financiers.
</p><p class="p1">11.4. Il est strictement interdit d'utiliser votre compte Edinars à des fins illégales incluant, en autres, la fraude et le blanchiment d'argent. Edinars signalera toute activité suspecte à l'organisme compétent chargé de faire appliquer la loi. Il vous est interdit d'utiliser votre compte Edinars pour essayer d'abuser, d'exploiter ou de contourner les restrictions d'utilisation imposées par un marchand sur les services qu'il fournit.
</p><p class="p1">11.5. Vous ne pouvez accepter des paiements que pour certaines catégories d'affaires après avoir reçu l'aval d’Edinars à sa seule discrétion. De telles catégories d'affaires incluent, sans y être limitées :
<br>•	les entreprises d'échange ou de virement de fonds, incluant, mais sans y être limitées, les bureaux de change, d’échange de devises et d'achat d'argent de voyage;
<br>•	la collecte de toute forme de donations ou de paiements destinés à des organismes caritatifs ou non lucratifs;
<br>•	le commerce de ressources naturelles telles que les bijoux, les pierres ou les métaux précieux ;
<br>•	la vente ou la fourniture de boissons alcoolisées ; ou
<br>•	la vente ou la fourniture de compléments diététiques et de produits de santé alternatifs ;
<br>•	n'importe quelle autre catégorie d'affaires publiée dans les activités interdits sur le site ;
<br>Au cas où vous n’arriveriez pas à déterminer si vos affaires tombent dans l'une ou l’autre de ces catégories, vous devez contacter le service clientèle.
Edinars se réserve le droit d'ajouter, à seule discrétion, des catégories commerciales exigeant une approbation en ajoutant de telles catégories aux présentes conditions d'utilisation ou à une politique d'utilisation acceptable publiée sur le site.
</p><p class="p1">11.6. Si vous menez ou essayez de mener toute transaction violant les interdictions contenues dans cette section 11 ou sans l'approbation nécessaire comme mentionnée à la section 11.5, nous nous réservons le droit :
<br>•	d’annuler la transaction ; et/ou
<br>•	de fermer ou de suspendre votre compte ; et/ou
<br>•	de signaler la transaction à l'organisme compétent chargé de faire appliquer la loi ; et/ou
<br>•	de vous réclamer des dommages ; et
<br>•	de vous imputer des frais de gestion jusqu'à 2500 DA au cas où nous appliquerions l'une des mesures citées ci-dessus.</p>
<p class="p1">11.7. Il est de votre responsabilité et non celle de Edinars de vous assurer que vos paiements concernent uniquement des personnes ou des entités en compensation de la vente ou de la fourniture de biens et de services que vous avez le droit de fournir ou de recevoir conformément à toutes les lois et à tous les règlements applicables. Le seul fait qu'une personne ou une entité accepte des paiements via Edinars n'est pas une indication de la légalité de la fourniture de ses biens ou de la prestation de des services. Si vous êtes dans le doute quant à la légalité d'une fourniture ou d'un achat, vous devez cesser votre paiement.
</p><p class="pTitle">12. Retrait de fonds
</p><p class="p1">12.1. Vous pouvez demander le retrait de l'ensemble ou d’une partie des fonds placés sur votre compte Edinars à tout moment. Pour ce faire, vous devez vous connecter à votre compte, choisir un mode de retrait et saisir le montant à retirer. Les modes de retrait sont des services de paiement fournis, au moins en partie, par des institutions financières tierces (par exemple, la banque où vous détenez un compte bancaire). Edinars ne garantit la disponibilité d'aucun mode de retrait particulier et peut rendre disponible, modifier ou cesser un mode de retrait particulier à tout moment sans suivre la procédure présentée dans la clause 18, tant qu'il y a au moins un mode de retrait à votre disposition. Si le paiement par retrait est reçu par vous par l'intermédiaire d'un fournisseur de services de paiement (tel que la banque où vous détenez un compte bancaire), Edinars ne sera plus responsable du paiement par retrait une fois que les fonds retirés sont reçus par votre fournisseur de services de paiement.
</p><p class="p1">12.2. Votre compte est sujet à des limites de retrait. Ces limites sont ajustées dynamiquement en fonction du type de document d'identité que nous détenons vous concernant. Vous pouvez consulter vos limites de retrait à tout moment dans le profil de votre compte. Avant de charger quelque fonds que ce soit sur votre compte, vous devez vous assurer que vos limites de retrait et de dépense actuelles répondent aux exigences de retrait et de dépense qui vous sont imposées car nous ne pouvons légalement pas vous permettre de dépasser ces limites.
</p><p class="p1">12.3. Si votre demande de retrait dépasse la limite actuelle, nous pouvons refuser votre demande et, en revanche, vous demander de nous envoyer des documents confirmant votre identité et votre adresse avant d’autoriser un retrait de fonds ou bien de coopérer avec nous pour vérifier votre identité.
</p><p class="p1">12.4. Les retraits sont sujets aux frais de retrait et de conversion de devise en fonction du mode de retrait et de l'instrument de paiement choisis. Veuillez consulter la section 14 pour de plus amples détails.
</p><p class="p1">12.5. En ce qui concerne les transactions de retrait, Edinars est un débiteur et non pas un fournisseur de services de paiement.
</p><p class="p1">12.6. Vous ne devez pas effectuer de retrait au crédit d’un compte bancaire ni de tout autre instrument de paiement si vous n'êtes pas le détenteur désigné. Nous prenons toute violation de cette condition très au sérieux et traiterons n'importe quelle tentative d'utilisation d’un instrument de paiement dont vous n'êtes pas le détenteur désigné comme un acte frauduleux. Sous réserve de tout droit de réclamation de dommages ultérieurs, si nous sommes contraints d’enquêter sur un chargement effectué depuis un instrument de paiement qui n'est pas à votre nom, nous pouvons facturer des frais de gestion de 1000 DA.
</p><p class="p1">12.7. Vous devez vous assurer que les détails de paiement que vous saisissez lorsque vous retirez des fonds sont corrects et complets. Edinars ne sera pas responsable des fonds retirés et envoyés à un instrument de paiement erroné s’il s’avère que cette erreur est due aux détails de paiement incorrects que vous avez fournis. Lorsque vous effectuez un retrait au crédit d’un compte bancaire ou CCP, vous devez vous assurer que le numéro de compte, le code guichet, le code RIB ou RIP sont corrects. Si vous avez retiré des fonds au crédit d’un instrument de paiement erroné, vous pouvez nous demander de vous aider à récupérer les fonds ; cependant, nous vous facturerons des frais de gestion de 1500 DA pour ce service et nous ne pouvons pas garantir que ces efforts de récupération aboutiront.
</p><p class="pTitle">13. Service de dépôt fiduciaire Edinars
</p><p class="p1">13.1. Les paiements via Edinars peuvent être sujets à notre service de dépôt fiduciaire. Cela vous permet d'effectuer un paiement au crédit d’un bénéficiaire, sous réserve de votre approbation de la transaction ultérieurement.
</p><p class="p1">13.2. Le service de dépôt fiduciaire est sujet aux conditions générales du service de dépôt fiduciaire. Si vous optez pour un paiement par le service de dépôt fiduciaire, vous acceptez d'être liés par les conditions générales du service de dépôt fiduciaire en plus des présentes conditions d'utilisation.
</p><p class="pTitle">14. Frais
</p><p class="p1">14.1. Les frais varient si vous utilisez votre compte à des fins personnelles ou à des commerciales.
</p><p class="p1">14.2. Les frais liés aux transactions peuvent être consultés à tout moment dans la section Frais sur notre site. Des surtaxes s'appliquent aux comptes Edinars utilisés à des fins commerciales. Il est recommandé d’imprimer ou de télécharger une copie de la section « Frais » ainsi que des présentes conditions d'utilisation et de les conserver. Les frais sont sujets à modification conformément à la section 18. Dans certaines circonstances, nous pouvons appliquer des frais supplémentaires, comme expliqué dans les clauses 8.3, 8.8, 11.6, 12.6 et 12.7.
</p><p class="p1">14.3. Vos transactions peuvent être sujettes à des conversions de devise. Si vous achetez d'un fournisseur à l'étranger conventionné avec Edinars.
</p><p class="p1">14.4. Pour chaque conversion de devise, Edinars appliquera le taux de conversion indiqué sur notre site. En outre, nous appliquerons des frais de devises étrangères, qui sont également indiqués dans la section « Frais » du site et qui sont exprimés en pourcentage applicable, en plus des frais de transaction.
</p><p class="p1">14.5. Nos frais sont soit exprimés en pourcentage de la transaction soit en montant fixe en Dinar. Si des montants de frais fixes sont indiqués dans une devise autre que le Dinar, c'est à titre informatif uniquement. Si des frais sont déduits d'un solde ou d'une transaction exprimés dans une devise différente, le montant des frais en Dinar sera converti en frais équivalents dans cette autre devise, sur la base du taux de conversion applicable à ce moment-là, et ensuite déduit. Nous n'appliquerons pas de frais d’échange de devises étrangères sur des conversions de devise qui concernent des frais.
</p><p class="p1">14.6. Les frais payables par vous seront déduits du solde de votre compte Edinars. Des frais de transaction seront facturés quand la transaction sera exécutée. Si le solde de votre compte est insuffisant pour couvrir les frais, nous pouvons refuser d'exécuter le paiement. Des frais d'annulation ou de chargeback seront déduits si encourus.
</p><p class="p1">14.7. Si la déduction des frais a pour conséquence un solde négatif sur votre compte, il vous sera demandé de rembourser ce solde négatif en chargeant des fonds suffisants sur votre compte Edinars. Le manquement à cette demande est une infraction aux présentes conditions d'utilisation. Le remboursement du solde négatif est dû immédiatement sans communication préalable ; cependant, nous nous réservons le droit à tout moment de vous envoyer les rappels dont vous avez besoin pour télécharger des fonds ou de prendre d'autres mesures de recouvrement de dettes, dont, entres autres, mandater une agence de recouvrement de dettes ou des avocats-conseils ou réclamer l'indemnisation devant le tribunal. Nous nous réservons le droit de vous facturer les dépenses que nous avons raisonnablement encourues dans le cadre d’un recouvrement de dettes ou de mesures contraignantes.
</p><p class="pTitle">15. Vos données
</p><p class="p1">15.1. Le traitement de vos données est régi par notre Politique en matière de protection de la vie privée, qui peut également être trouvée sur notre site. En acceptant les présentes conditions d’utilisation, vous êtes également d'accord sur les termes de notre politique en matière de protection de la vie privée. Il est recommandé d'imprimer et conserver une copie de notre politique en matière de protection de la vie privée ainsi que des présentes conditions d'utilisation.
</p><p class="p1">15.2. Edinars collecte, enregistre et traite vos données conformément à la loi algérienne. Aucune donnée n'est stockée par nous en dehors de l'Algérie ou Canada; cependant, afin de vous fournir certains services frontaliers, nous pouvons être amenés à partager vos données avec des entités en dehors de l'Algérie. En effectuant des paiements en faveur ou en acceptant des paiements provenant de personnes ou d’entités en dehors de l'Algérie, vous consentez à ce que nous partagions vos données avec des entités en dehors de l'Algérie dans la mesure où cela est raisonnablement nécessaire pour l'exécution appropriée des paiements ou la prestation de nos services.
</p><p class="p1">15.3. Si vous détectez toute erreur dans les données que nous détenons sur vous, vous devez corriger les données dans le profil de votre compte ou, si ce n'est pas possible, en contactant le service clientèle.
</p><p class="p1">15.4. Par défaut, vous recevrez des newsletters par e-mail qui vous informeront sur les caractéristiques des nouveaux produits, les événements, les promotions, les offres spéciales, etc. En acceptant les présentes conditions d’utilisation, vous acceptez de recevoir de telles newsletters par e-mail de façon régulière. Si vous ne souhaitez pas recevoir de newsletter de notre part, vous pouvez choisir à tout moment de vous connecter à votre compte et de changer les paramètres appropriés dans le profil de votre compte. Vous pouvez également cesser de recevoir des newsletters en contactant le service clientèle. Chaque e-mail de newsletter que vous recevez vous donnera également la possibilité de vous désinscrire pour les futures newsletters.
</p><p class="p1">15.5. Après que la clôture de votre compte Edinars pour quelque raison que ce soit, nous conserverons les données de votre compte personnel pour une période de cinq ans ou tout autre période prescrite par la loi en vigueur.
</p><p class="pTitle">16. Responsabilité
</p><p class="p1">16.1. En cas de paiement non autorisé ou d’un paiement qui a été exécuté erronément dû à une erreur d’Edinars, Edinars remboursera immédiatement à votre demande le montant du paiement comprenant tous les frais déduits de la somme en question. Ceci ne s'appliquera pas :
</p><p class="p1">16.1.1. Si le paiement non autorisé résulte de votre manquement à préserver la sûreté des caractéristiques de sécurité personnalisées de votre compte conformément à la section 6 auquel cas vous resterez redevable des mille premiers dinars sauf si la clause 16.1.3 est d'application;
</p><p class="p1">16.1.2. Si vous ne nous informez pas promptement de la perte de votre mot de passe ou de tout autre événement dont on pourrait raisonnablement s’attendre à ce qu’il compromette la sécurité de votre compte après avoir pris connaissance d'un tel événement et vous resterez responsable des pertes encourues jusqu'au moment où vous nous en informez ;
</p><p class="p1">16.1.3. S'il s’avère que la transaction n’était pas autorisée et que vous avez compromis la sécurité de votre compte Edinars de façon intentionnelle ou par négligence grave, auquel cas vous serez tenu pour unique responsable de toutes pertes ; ou
</p><p class="p1">16.1.4. Si vous ne contestez pas et ne portez pas la transaction non autorisée ou inexactement exécutée à l’attention d’Edinars dans les treize mois de la date de la transaction.
</p><p class="p1">16.2. La section 16.1.1 ne s'appliquera pas aux transactions effectuées après que vous nous avez mis au courant, conformément à la section 6.2, auquel cas Edinars restera responsable et vous remboursera immédiatement toute transaction non autorisée.
</p><p class="p1">16.3. Sous réserve de ce qui précède, vous êtes invité à vérifier l'historique de transactions de votre compte Edinars régulièrement et fréquemment et à contacter le service clientèle immédiatement pour toutes questions ou problèmes.
</p><p class="p1">16.4. Dans le cas de paiements incorrects ou mal dirigés, Edinars prendra des mesures raisonnables pour vous aider à retrouver et à récupérer ces paiements.
</p><p class="p1">16.5. Sous réserve de ce qui précède, Edinars ne sera tenu pour responsable d’aucune interruption ou perturbation de son service ni des interruptions ou des perturbations des services intermédiaires sur lesquels Edinars se fonde pour le respect de ses engagements ci-dessous, à condition qu’une telle interruption ou perturbation soit due à des circonstances anormales et imprévues indépendantes de son contrôle raisonnable ou du contrôle de l'intermédiaire concerné.
</p><p class="p1">16.6. Edinars ne sera responsable d'aucunes pertes indirectes ou consécutives incluant, sans y être limitées, le manque à gagner, la perte de clients et le ternissement de réputation. Edinars ne sera tenue responsable d'aucune perte résultant de notre respect de la loi et de règlements de régulation.
</p><p class="p1">16.7. Rien dans les présentes conditions d'utilisation n’est prévu pour exclure la responsabilité en cas de mort ou de dommage corporel causés par négligence ou en cas de fraude, de déclaration frauduleuse ou de n'importe quelle responsabilité statutaire qui ne peut pas être exclue ou modifiée par un accord entre les parties.
</p><p class="p1">16.8. L’engagement de Edinars en vertu des présentes conditions d'utilisation se limite à vous fournir un compte Edinars et des services de paiement connexes et ne commente ni ne cautionne la qualité, la sécurité ou la légalité des biens ou des services fournis par un client de Edinars.
</p><p class="p1">16.9. Edinars ne sera responsable de l'estimation ou du paiement d'aucun impôt, d’aucune taxe ni d’aucune autre charge résultant de la transaction commerciale initiale entre vous et un autre client de Edinars.
</p><p class="pTitle">17. Clôture et suspension
</p><p class="p1">17.1. Nous pouvons clôturer votre compte Edinars ou n'importe quel service de paiement lié à celui-ci sans vous donnant de préavis. Vous pouvez clôturer votre compte à tout moment. Différents droits de clôture peuvent s'appliquer selon les termes d'un accord marchand si vous détenez un compte de négociant.
</p><p class="p1">17.2. En même temps qu'une notification de clôture ou à tout moment par la suite, nous pouvons vous donner des instructions raisonnables sur la façon dont vous pouvez retirer les fonds restants.
</p><p class="p1">17.3. Si votre compte est sujet à une réserve, la clôture de votre compte n'altérera pas notre droit de garder la réserve et d’y faire les déductions nécessaires pour la période convenue.
</p><p class="p1">17.4. Nous pouvons à tout moment suspendre ou clôturer votre compte Edinars sans communication préalable :
</p><p class="p1">17.4.1. Si vous contrevenez à l’une des clauses des présentes conditions d'utilisation ou à tout autre clause applicable aux services spécifiques couverts par des conditions générales séparées ;
</p><p class="p1">17.4.2. Si vous violez ou si nous avons des raisons de croire que vous êtes en infraction à toute loi ou à tout règlement qui s'applique à votre utilisation des services Edinars ; ou
</p><p class="p1">17.4.3. Si nous avons des raisons de croire que vous êtes de quelque façon que ce soit impliqué dans toute activité frauduleuse, de blanchiment d'argent, de financement d’actes terroristes ou toute autre activité criminelle.
</p><p class="p1">17.5. Nous pouvons suspendre votre compte à tout moment :
</p><p class="p1">17.5.1. Si nous croyons raisonnablement que votre compte a été compromis ou pour d'autres raisons de sécurité ; ou
</p><p class="p1">17.5.2. Si nous suspectons raisonnablement que votre compte a été utilisé ou est utilisé sans votre autorisation ou frauduleusement ; en outre, nous vous informerons soit avant la suspension soit, si le préavis n'est pas possible vu les circonstances, promptement après la suspension à moins que nous en soyons interdits légalement.
</p><p class="pTitle">18. Modifications des présentes conditions d'utilisation
</p><p class="p1">18.1. Les présentes conditions d'utilisation et toutes les conditions générales additionnelles qui peuvent s'appliquer aux services complémentaires sont sujettes à modification. Les modifications seront mises en application avec notification préalable d’Edinars selon la procédure déterminée dans la présente section.
</p><p class="p1">18.2. Edinars vous notifiera de toute modification proposée en envoyant un e-mail à l'adresse principale enregistrée dans votre compte.
</p><p class="p1">18.3. La modification proposée entrera en vigueur deux mois après la date de la notification de modification, à moins que vous nous ayez notifié que vous vous opposez aux modifications proposées avant que celles-ci n’entrent en vigueur. Les modifications qui rendent les présentes conditions d'utilisation plus favorables pour vous entreront en vigueur immédiatement, pour autant que cela soit indiqué dans la notification de modification. Les modifications des taux de change entreront en vigueur immédiatement sans communication préalable et vous n'aurez pas le droit de vous opposer à de telles modifications.
</p><p class="p1">18.4. Si vous vous opposez aux modifications, elles ne s'appliqueront pas à vous ; cependant, une telle objection de votre part constituera une notification de fin et de clôture de votre compte.
</p><p class="pTitle">19. Notre mode de communication
</p><p class="p1">19.1. Nous communiquons habituellement avec vous par e-mail. À cet effet, vous devez à tout moment avoir au moins une adresse e-mail valable dans le profil de votre compte. Vous êtes tenu de vérifier les messages entrants régulièrement et fréquemment. Les e-mails peuvent contenir des liens vers des communications ultérieures sur notre site.
</p><p class="p1">19.2. Si la législation exige que nous vous fournissions des informations sur un support durable, nous vous enverrons un e-mail (avec ou sans pièce jointe) ou nous vous enverrons une notification vous renvoyant à des informations sur notre site d'une manière qui vous permettra de conserver les informations dans un format d'impression ou dans un autre format qui peut être conservé par vous de manière permanente pour référence future. Vous êtes tenu de conserver des copies de toutes les communications que nous vous envoyons ou que nous mettons à votre disposition.
</p><p class="p1">19.3. Vous pouvez demander une copie des conditions d'utilisation actuelles ou de n'importe quel autre document contractuel vous concernant en contactant le service clientèle.
</p><p class="p1">19.4. Afin de consulter vos e-mails, vous avez besoin d'un ordinateur avec un logiciel d'e-mail qui peut afficher des e-mails au format HTML. Nous pouvons également vous envoyer des pièces jointes au format PDF (Portable Document Format d’Adobe Systems Inc.), pour lequel vous avez besoin du logiciel Acrobat Reader d'Adobe, qui peut être téléchargé gratuitement sur www.adobe.com.
</p><p class="p1">19.5. Nous ne vous enverrons jamais aucun e-mail avec des fichiers exécutables en pièce jointe ou avec des liens renvoyant à des fichiers exécutables. Si vous recevez un e-mail avec de telles pièces jointes, vous devez supprimer le message sans cliquer sur la pièce jointe. Si vous n’êtes pas sûr qu’une communication vienne de nous, contactez notre service clientèle.
</p><p class="p1">19.6. Nous communiquerons avec vous en Arabe ou Français et accepterons toujours des communications à notre attention en arabe ou français. Vous pouvez choisir votre langue préférée dans la liste des langues prises en charge dans le profil de votre compte et nous vous enverrons des notifications et des communications par e-mail automatisé concernant les modifications apportées aux présentes conditions d'utilisation dans la langue de votre choix. Pour les communications non standard, nous nous réservons le droit de communiquer avec vous en arabe ou en français. Les documents ou les communications peuvent être transmis dans d’autres langues à des fins pratiques uniquement et ne constitueront pas une obligation de notre part de continuer à communiquer dans cette langue.
</p><p class="p1">19.7. Indépendamment de la communication par e-mail, nous pouvons vous contacter par lettre ou par téléphone, le cas échéant. Si vous utilisez des services mobiles, nous pouvons communiquer avec vous par SMS.
</p><p class="p1">19.8. Vous pouvez nous contacter à tout moment en envoyant un message au service clientèle via le service « Contacter nous » sur notre site ou en appelant au +213 21 77 0202,  +213 21 77 0303.
</p><p class="pTitle">20. Plaintes
</p><p class="p1">20.1. Toutes les plaintes concernant Edinars ou les services que nous fournissons doivent nous être adressées en premier lieu par le biais du service clientèle. Vous devez clairement indiquer que vous souhaitez déposer une plainte contre nous. Cela nous aide à distinguer une plainte d'une simple question. Nous accuserons réception des plaintes dans les cinq jours ouvrables. Vous pouvez demander à recevoir une copie de notre procédure de plaintes à tout moment.
</p><p class="p1">20.2. Nous faisons en sorte de fournir une réponse ou une résolution à votre plainte dans des délais raisonnables. Si ce n'est pas possible dû à des circonstances imprévues ou à un manque d'informations, nous vous contacterons.
</p><p class="pTitle">21. Divers
</p><p class="p1">21.1. Les présentes conditions d'utilisation ne confèrent aucun droit à une autre personne que vous.
</p><p class="p1">21.2. Votre compte Edinars vous est personnel et vous ne pouvez attribuer aucun droit à aucun tiers en vertu des conditions d'utilisation.
</p><p class="p1">21.3. Votre compte Edinars est géré à Alger et les présentes conditions d'utilisation seront régies par et interprétées selon les lois d'Algérie. Tout litige en vertu des présentes conditions d'utilisation ou bien en rapport avec votre compte Edinars sera porté exclusivement devant la cour d'Alger.
</p>
<p class="pTitle">22. Définitions</p>
<p class="p1">
Les diverses clauses des présentes conditions d'utilisation ont une signification bien définie ; vous trouverez les différentes définitions ci-après :
“Service clientèle” : le service clientèle d’Edinars, que vous pouvez joindre en envoyant un message via le service « Contact » sur le site ou en appelant au <?=$data['ContactNumber']?></p>
</p>
<br>
<BR>
	
		</div>
	</article>
	<div class="clr"></div>

</div>

<!-- End content  -->

