<!-- Start content  -->

<div class="content">
    <article class="col-3">
        <div class="col_title">Conditions d'utilisation de Erecovery</div>
        <div class="col_text">
            <p class="p1">Voici les termes et conditions applicables lorsque vous consentez � utiliser nos services</p>

                            <p class="pTitle">1. A propos de Erecovery </p>
                                <p class="p1">1.1. Sarl Erecovery est une soci�t� constitu�e en vertu des lois de la R�publique Alg�rienne D�mocratique et Populaire portant le num�ro de matricule fiscale . Inscrit au Registre de Commerce sous le n�: , dont le si�ge est sis �: </p>
                            <p class="pTitle">2. Port�e des pr�sentes conditions d'utilisation</p>
                                <p class="p1">2.1. Les pr�sentes conditions d'utilisation r�gissent l'ouverture, l�utilisation et la cl�ture de votre compte Erecovery. En m�me temps que notre Politique en mati�re de protection de la vie priv�e, elles constituent le lien l�gal entre vous et nous. Pour l'usage des services compl�mentaires, il se peut que vous deviez accepter des conditions g�n�rales additionnelles, comme vous y �tes invit�s lorsque vous commandez ou utilisez de tels services. Il vous est conseill� d'imprimer ou de t�l�charger une copie des pr�sentes conditions d'utilisation et de la conserver pour r�f�rence ult�rieure. Vous pouvez toujours consulter les derni�res conditions d'utilisation sur notre site.</p>
                                <p class="p1">2.2. Il vous est �galement conseill� de lire les r�ponses aux questions fr�quemment pos�es sur notre site.</p>
                                <p class="p1">2.3. Selon le type de compte que vous avez, des conditions g�n�rales additionnelles peuvent s'appliquer comme cela vous sera communiqu� au moment opportun.</p>
                            <p class="pTitle">3. Votre compte Erecovery</p>
                                <p class="p1">3.1. Votre compte Erecovery est un compte de gestion de vos op�rations de paiement �lectronique, qui vous permet d'envoyer et de recevoir des paiements �lectroniques.</p>
                                <p class="p1">3.2. L'argent sur votre compte est un pr�paiement sur vos prochaines op�rations, vous donne autorisation � la Sarl Erecovery � payer les fournisseurs ou les prestataires conventionn�s � votre place en utilisant votre solde, qu'est toujours visible dans votre compte.</p>
                                <p class="p1">3.3. Votre compte Erecovery est exprim� dans la devise nationale DZD (Dinar Alg�rien). Et votre compte est valable uniquement pour payer des fournisseurs ou prestataires install�s en Alg�rie.</p>
                                <p class="p1">3.4. L'argent contenu sur votre compte Erecovery ne perd jamais sa valeur mais il ne rapportera aucun int�r�t.</p>
<p class="p1">3.5. Vous avez le droit de retirer votre argent de votre compte Erecovery � tout moment ; cependant, il peut vous �tre demand� de confirmer votre identit� au pr�alable. Il n'y a aucun montant de retrait minimum mais les fonds sur votre compte doivent �tre suffisants pour couvrir tout �ventuel frais de retrait applicable. Vous pouvez choisir la m�thode de retrait en soumettant votre demande de retrait.</p>
<p class="p1">3.6. Les comptes Erecovery ne sont pas des comptes bancaires. En acceptant les pr�sentes conditions d�utilisation, vous reconnaissez que les Autorit�s Financi�res Alg�riennes ne s�appliquent pas � votre compte Erecovery. Dans le cas peu probable o� SARL Erecovery devenait insolvable, vous pourriez perdre l'argent plac� sur votre compte. Cependant, SARL Erecovery respecte rigoureusement les exigences l�gales prescrites par les autorit�s pour assurer la s�curit� et la liquidit� des fonds d�pos�s sur des comptes Erecovery. Pour de plus amples informations sur la fa�on dont nous pr�servons la s�curit� des fonds de nos clients, veuillez consulter notre site Internet.</p>
<p class="p1">3.7. L'argent plac� sur un compte Erecovery appartient � la personne ou � la personne morale qui est enregistr�e en tant que d�tenteur du compte. Aucune autre personne que le d�tenteur du compte n'a de droit sur les fonds plac�s sur un compte Erecovery, except� dans les cas de succession. Vous ne pouvez pas attribuer ou transf�rer votre compte Erecovery � un tiers ni accorder un int�r�t l�gal ou �quitable sur celui-ci � un tiers.</p>
<p class="p1">3.8. Votre compte Erecovery peut �tre sujet � des limites de d�p�t, de paiement et de retrait, selon votre statut de v�rification de votre compte Erecovery.</p>
<p class="pTitle">4. Ouverture de votre compte</p>
<p class="p1">4.1. Afin d�utiliser les services de paiement Erecovery, vous devez d'abord ouvrir un compte Erecovery en enregistrant vos coordonn�es sur notre site www.Erecovery. En tant qu'�l�ment du processus d'inscription, vous devrez accepter ces limites d'utilisation ainsi que notre politique en mati�re de protection de la vie priv�e. Si vous commandez des services compl�mentaires, vous pouvez �tre invit� � accepter des conditions g�n�rales additionnelles. Il vous est recommand� d�imprimer et de conserver une copie des pr�sentes conditions d'utilisation pour r�f�rence ult�rieure.</p>
<p class="p1">4.2. Vous devez �tre �g� d�au moins 18 ans pour utiliser nos services et, en ouvrant un compte Erecovery, vous d�clarez que vous �tes �g� d�au moins 18 ans. Cela ne s'applique pas aux produits pour lesquels nous fixons une limite d'�ge diff�rente. Nous pouvons vous demander � tout moment de prouver votre �ge.</p>
<p class="p1">4.3. Vous ne pouvez ouvrir qu'un compte Erecovery � moins que nous approuvions explicitement l'ouverture de comptes suppl�mentaires.</p>
<p class="p1">4.4. Vous ne pouvez ouvrir un compte Erecovery que si cela est l�gal dans votre pays de r�sidence. En ouvrant un compte, vous indiquez et vous nous garantissez qu�en ouvrant un compte, vous ne violez aucunes des lois ni aucun des r�glements qui vous sont applicables. Vous nous indemniserez contre toutes les pertes que nous encourrons � la suite de toute infraction � cette section de votre part.</p>
<p class="p1">4.5. Toutes les informations que vous fournissez lors du processus d'inscription ou n'importe quand par la suite doivent �tre pr�cises et v�ridiques.</p>
<p class="p1">4.6. Vous ne pouvez ajouter des instruments de paiement (tels que des comptes bancaires, des cartes de cr�dit ou des cartes de d�bit) � votre compte Erecovery que si vous �tes le d�tenteur d�sign� de cet instrument de paiement. Nous prenons toute violation de cette condition tr�s au s�rieux et traiterons n'importe quelle tentative d'ajout d�un instrument de paiement dont vous n'�tes pas le d�tenteur d�sign� comme un acte frauduleux.</p>
<p class="p1">4.7. Pendant l'inscription, il vous sera demand� si vous avez l'intention d'utiliser votre compte Erecovery � des fins priv�es ou commerciales. Si vous avez l�intention d'utiliser votre compte � des fins commerciales, vous devez nous le dire, m�me si vous l'utilisez �galement � des fins priv�es. Si vous avez d�clar� que vous utiliserez votre compte � des fins priv�es uniquement, vous devez nous dire si, � un moment quelconque dans le futur, vous l'utiliserez � des fins commerciales en contactant le service client�le. Vous utilisez votre compte � des fins commerciales si vous recevez des paiements pour ou concernant une activit� �conomique quelconque. Nous nous r�servons le droit de d�terminer si, � notre avis raisonnable, vous utilisez votre compte � des fins commerciales. Si vous utilisez votre compte � des fins commerciales, en plus des pr�sentes conditions d'utilisation, vous serez li� par nos conditions g�n�rales pour marchands (disponibles sur https://www.Erecovery/docs/merchantstos/) et vous payerez des frais tels qu'indiqu�s sur notre page de tarifs marchands (disponibles sur http://www.Erecovery/docs/merchantfees/). Si vous n'arrivez pas � d�terminer si une activit� s�apparente � une activit� commerciale, vous devez entrer en contact avec le service client�le.</p>
<p class="p1">4.8. Dans les quinze jours de la date d'ouverture de votre compte Erecovery, vous pouvez cl�turer votre compte gratuitement en contactant le service client�le ; cependant, si vous avez verser des fonds sur votre compte Erecovery, vous pouvez �tre tenu de fournir des documents d'identit� avant de pouvoir retirer des fonds. Les transactions et les frais pour des transactions effectu�es avant que vous ne cl�turiez votre compte (y compris les transactions qui ne sont pas r�vocables et qui ont �t� lanc�es mais pas achev�es avant la fermeture de compte) ne seront pas rembours�s.</p>
 <p class="pTitle">5. Gestion de votre compte</p>
<p class="p1">5.1. Vous devez vous assurer que les informations enregistr�es sur votre compte Erecovery sont toujours pr�cises et � jour et nous ne serons tenus pour responsables d'aucune perte si vous ne le faites pas. Nous pouvons vous demander � tout moment de confirmer l'exactitude de vos informations ou de fournir des documents ou toute autre preuve.</p>
<p class="p1">5.2. Nous pouvons vous contacter par e-mail ou de diverses autres mani�res comme nous le d�crivons dans la section 19 d�informations ou dans les notifications concernant votre compte Erecovery. Il est de votre responsabilit� de v�rifier r�guli�rement le bon fonctionnement de votre compte e-mail ou des autres m�thodes de communication que vous avez enregistr�es dans votre compte et de r�cup�rer et de lire promptement les messages concernant votre compte. Nous ne serons responsables d'aucune perte si vous ne le faites pas.</p>
<p class="p1">5.3. Les chargement de cr�dit, les paiements re�us, les paiements envoy�s et les retraits de cr�dit sont indiqu�s dans votre historique de transactions en ligne avec les frais imput�s. Un code unique d'identification de transaction est attribu� � chaque transaction et est affich� dans l'historique des transactions. Vous devez mentionner ce code d'identification de transaction pour toute communication avec nous au sujet d'une transaction particuli�re. Vous devez v�rifier l�historique du solde et des transactions de votre compte r�guli�rement. </p>
Vous devez signaler toutes les irr�gularit�s ou clarifier toutes les questions que vous pourriez avoir d�s que possible en contactant le service client�le.</p>
<p class="pTitle">6. Maintien de la s�curit� de votre compte Erecovery</p>
<p class="p1">6.1. Vous devez pr�server la s�curit� du mot de passe de votre compte � tout moment et ne jamais le r�v�ler � qui que ce soit. Notre personnel ne vous demandera jamais de lui fournir votre mot de passe ou de le donner � un tiers. Tout message que vous recevez ou tout site que vous consultez vous demandant votre mot de passe, en dehors du site d�Erecovery ou d�une passerelle de paiement Erecovery sur le site d�un n�gociant, doit nous �tre signal�. Si vous doutez de l�authenticit� d�un site, vous devez contacter le service client�le. Vous devez changer votre mot de passe r�guli�rement et vous ne devez jamais :
<br>�    Noter ou stocker votre mot de passe o� que ce soit ;
<BR>�    Autoriser quelqu'un � acc�der � votre compte ou � vous regarder acc�der � votre compte ;
<br>�    Choisir un mot de passe qui est peut-�tre facilement devin� par quelqu'un qui pourrait utiliser ou recueillir des informations sur vous; ou
<br>�    Choisir un mot de passe qui a un sens.</p>
<p class="p1">6.2. Si vous avez des signes ou soup�ons concernant la perte, le vol, le d�tournement, l�utilisation non autoris�e voire la divulgation de votre login, de votre mot de passe ou de tout autre dispositif de s�curit�, vous devez changer votre mot de passe et contacter le service client�le imm�diatement. Si vous tardez de mani�re injustifi�e � nous en informer, cela peut non seulement compromettre la s�curit� de votre compte mais vous pourriez �galement �tre tenu pour responsable de toutes les pertes qui en r�sultent. Si vous suspectez que quelqu'un d'autre a acc�d� � votre compte, vous devez �galement contacter la police et signaler l'incident.</p>
<p class="p1">6.3. Nous pouvons � tout moment suspendre ou bien limiter la fonctionnalit� de votre compte si nous suspectons qu'on y a acc�d� sans votre autorisation ou qu'il a �t� compromis de quelque mani�re que ce soit.</p>
<p class="p1">6.4. Vous devez �galement faire tout ce qui est raisonnablement n�cessaire pour vous assurer que vos comptes e-mail sont s�curis�s et que vous seul y acc�dez, car il se peut que votre adresse e-mail soit utilis�e pour r�initialiser des mots de passe ou pour communiquer avec vous au sujet de la s�curit� de votre compte. Au cas o� l'unes des adresses e-mails enregistr�es dans votre compte Erecovery serait compromise, vous devez imm�diatement contacter le service client�le ainsi que votre fournisseur de services e-mail.</p>
<p class="p1">6.5. Si vous utilisez un ordinateur public ou partag� pour acc�der � votre compte Erecovery, vous devez vous assurer que vos coordonn�es de connexion ne sont pas stock�es par le navigateur, mises en cache ou enregistr�es de quelque mani�re que ce soit. Si vous utilisez votre propre ordinateur, vous devez vous assurer que vous seul y avez acc�s. Vous ne devez jamais utiliser de fonctionnalit� qui permette le stockage de coordonn�es de connexion ou de mots de passe par l'ordinateur que vous utilisez.</p>
<p class="p1">6.6. Les produits ou les services additionnels que vous utilisez peuvent impliquer des exigences de s�curit� suppl�mentaires et vous devez vous familiariser avec celles-ci comme cela vous sera notifi�.</p>
<p class="pTitle">7. Cl�ture de votre compte</p>
<p class="p1">7.1. Vous pouvez cl�turer votre compte Erecovery � tout moment en contactant le service client�le.</p>
<p class="p1">7.2. Si votre compte contient un solde au moment de sa cl�ture, nous vous demanderons de retirer vos fonds dans un d�lai raisonnable au cours duquel votre compte sera accessible pour vous permettre de retirer le solde restant uniquement. Votre engagement � pr�server la s�curit� de votre compte comme stipul� dans la section 6 continuera � �tre d�application. Si vous ne retirez pas les fonds dans le d�lai fix�, nous pouvons (sans y �tre oblig�s) vous envoyer un ch�que � l'adresse enregistr�e dans le profil de votre compte Erecovery et vous facturerons les frais applicables aux retraits par ch�que (y compris les frais d'�mission et d'envoi de ch�que). Il est de votre responsabilit� de maintenir votre adresse � jour et nous ne serons responsables d'aucune perte r�sultant de votre manquement � celle-ci.</p>
<p class="p1">7.3. La cl�ture de votre compte ne fait pas dispara�tre les donn�es personnelles que nous d�tenons sur vous et nous continuerons � stocker de telles donn�es, y compris l'historique de transactions, pendant une p�riode minimum de cinq ans comme l�exige la loi.</p>
<p class="pTitle">8. D�p�t de fonds</p>
<p class="p1">8.1. Vous pouvez d�poser (charger) des fonds en visitant le site www.Erecovery, en vous connectant � votre compte et en suivant les instructions de chargement appropri�es. Un certain nombre de m�thodes de chargement diff�rentes peuvent vous �tre pr�sent�es, en fonction des instruments de paiement que vous avez ajout�s � votre compte Erecovery et des m�thodes de paiement disponibles dans votre pays de r�sidence. Les m�thodes de chargement sont des services de paiement fournis par des institutions financi�res tierces (par exemple, l'�metteur de la carte de paiement que vous utilisez pour charger des fonds ou des prestataires de service d'op�rations bancaires directes tiers) et ne font pas partie du service Erecovery. Erecovery ne garantit l'utilisation d'aucune m�thode de chargement particuli�re et peut rendre disponible, modifier ou cesser l'acceptation de toute m�thode de chargement particuli�re � tout moment sans suivre la proc�dure pr�sent�e dans la clause 18. Erecovery ne sera pas responsable du paiement charg� jusqu'� ce que les fonds charg�s soient re�us par Erecovery Sarl.</p>
<p class="p1">8.2. Vous pouvez �tre invit� � r�pondre � des questions de s�curit� ou � accomplir d'autres activit�s que nous pouvons raisonnablement exiger pour assurer l'autorisation appropri�e d'une transaction � chargement.</p>
<p class="p1">8.3. Si vous choisissez une m�thode de chargement utilisant un instrument de paiement qui peut �tre sujet � des droits de chargeback comme, entre autres, une carte de cr�dit ou de d�bit ou le d�bit direct, vous d�clarez que vous n'exercerez pas ces droits de chargeback pour autre chose que l'usage non autoris� de l'instrument de paiement ou pour une infraction de Erecovery aux pr�sentes conditions d'utilisation qui aurait pour cons�quence que vous ayez droit au remboursement du montant charg�. Vous ne pouvez appliquer de chargeback � une transaction � chargement ou autoriser le chargeback d�une transaction � chargement pour des raisons qui n�engage pas la responsabilit� de SARL Erecovery comme, entre autres, des litiges avec des n�gociants pour la non-livraison de biens ou de services ou un solde insuffisant sur le compte de l'instrument de paiement. Nous nous r�servons le droit de vous facturer des frais et des d�penses que nous encourons � la suite d�un tel chargeback et de toute action entreprise pour contester celui-ci. Nous pouvons �galement vous facturer des frais de chargeback de 1000 DA.</p>
<p class="p1">8.4. Vous pouvez permettre � un marchand que vous souhaitez payer au moyen d�Erecovery de fa�on r�guli�re (par exemple, pour un service d'abonnement) de d�biter votre compte Erecovery pour chaque paiement p�riodique. Dans ce cas, vous autorisez Erecovery � d�biter l'instrument de paiement (par exemple, votre carte de cr�dit ou votre compte bancaire) que vous avez utilis� pour effectuer le paiement original �galement pour tous les paiements suivants. Vous acceptez de ne pas supprimer ni annuler de telles transactions p�riodiques simplement en contactant l'�metteur de l'instrument de paiement (par exemple, votre fournisseur de carte de cr�dit ou votre banque). Afin d'annuler les paiements p�riodiques � l'avenir, vous devez (a) contacter Erecovery et (b) informer le n�gociant dont vous avez achet� les biens ou les services que vous avez annul� le paiement p�riodique. Vous pouvez �galement nous demander de rembourser tout paiement p�riodique pass� � condition que (a) l'autorisation initiale donn�e � nous ou au n�gociant ne sp�cifiait pas le montant exact du paiement et (b) que le montant du paiement d�passait la somme � laquelle vous pouviez raisonnablement vous attendre en consid�ration de votre mod�le de d�pense pr�c�dent et des circonstances du cas. Vous devez demander un tel remboursement dans un d�lai de quatre semaines � partir de la date � laquelle les fonds ont �t� d�bit�s de votre compte Erecovery.</p>
<p class="p1">8.5. Si le chargeback ou l�inversion du chargement d�une transaction a pour cons�quence un solde n�gatif sur votre compte, vous serez pri� de rembourser ce solde n�gatif en chargeant des fonds suffisants sur votre compte. Le manquement � cette demande est une infraction aux pr�sentes conditions d'utilisation. Le remboursement du solde n�gatif est d� imm�diatement sans communication pr�alable ; cependant, nous nous r�servons le droit, � tout moment, de vous envoyer des rappels ou de prendre d'autres mesures de recouvrement de dettes, y compris, entres autres, de mandater une agence de recouvrement de dettes ou des avocats-conseils ou de r�clamer une indemnisation devant le tribunal. Nous nous r�servons le droit de vous facturer les d�penses que nous encourons raisonnablement en entreprenant des d�marches de recouvrement de dettes ou des mesures contraignantes.</p>
<p class="p1">8.6. Les fonds charg�s seront cr�dit�s sur votre compte Erecovery le jour m�me o� les fonds sont re�us par SARL Erecovery. Centaines transactions � t�l�chargement, par exemple au moyen d�une carte de cr�dit ou de d�bit, par d�bit direct ou via des op�rations bancaires directes, seront cr�dit�es sur votre compte imm�diatement, mais sont sujettes � annulation au cas o� les fonds r�els n'atteindraient pas Erecovery dans un d�lai raisonnable, auquel cas SARL Erecovery d�duira cette transaction annul�e du solde de votre compte Erecovery. Si le solde de votre compte est insuffisant, nous nous r�servons le droit d'exiger un remboursement de votre part.</p>
<p class="p1">8.7. Dans le cadre d'une transaction � chargement au moyen d�un instrument de paiement, Erecovery est un receveur de paiement et non un fournisseur de services de paiement.</p>
</p><p class="p1">8.9. Les chargements peuvent �tre sujets � des limites de chargement pour des raisons de s�curit� et d�exigences l�gales. Ces limites sont fix�es dynamiquement selon votre statut de v�rification et la m�thode de chargement que vous voulez utiliser. Vous devez garder � l�esprit que, selon votre statut de v�rification, vos limites de chargement peuvent �tre sup�rieures � vos limites de retrait ou de d�pense. Vous pouvez consulter ces limites � tout moment dans la section correspondante du profil de votre compte.</p>
</p><p class="p1">8.10. Les chargements sont sujets � des frais de chargement et de conversion de devise en fonction de l'instrument de paiement et de la m�thode de chargement choisis. Veuillez consulter la section 14 pour de plus amples d�tails.</p>
</p><p class="pTitle">9. Envoi de paiements
</p><p class="p1">9.1. Pour envoyer � un paiement, vous devez d�abord autoriser le paiement avec votre login et votre mot de passe. Nous pouvons �galement vous poser des questions de s�curit� compl�mentaires en rapport avec vous ou votre compte. Si votre compte est prot�g� par des mesures de s�curit� suppl�mentaires telles que l'utilisation de tokens de mot de passe, vous devez suivre les instructions qui vous ont �t� fournies en m�me temps que ces mesures de s�curit� suppl�mentaires. Si votre compte est autoris� � effectuer des paiements en masse, la proc�dure pour effectuer de tels paiements vous sera communiqu�e dans le manuel d'int�gration appropri�.
</p><p class="p1">9.2. Chaque b�n�ficiaire d'un paiement que vous souhaitez envoyer via Erecovery doit avoir une adresse e-mail valable.
</p><p class="p1">9.3. Si vous �tes invit� � fournir l'adresse e-mail du b�n�ficiaire, vous devez faire tr�s attention � taper correctement l'adresse e-mail exacte � laquelle vous souhaitez envoyer l'argent. Erecovery utilise l'adresse e-mail comme identifiant unique pour d�terminer le b�n�ficiaire pr�vu du paiement que vous nous demandez de traiter. Toutes les autres informations que vous fournirez en plus de l'adresse e-mail du b�n�ficiaire sont susceptibles de ne pas �tre prises en compte sauf l'identifiant de compte Erecovery, et nous ne serons pas responsables des erreurs que vous pourriez faire en saisissant l'adresse e-mail du b�n�ficiaire.
</p><p class="p1">9.4. Si l'adresse e-mail du b�n�ficiaire pr�vu est enregistr�e dans Erecovery, les fonds seront imm�diatement cr�dit�s au compte Erecovery li� � cette adresse e-mail, � moins que vous utilisiez le service de d�p�t fiduciaire de Erecovery comme d�crit dans la section 13. Une fois que les fonds sont cr�dit�s au compte du b�n�ficiaire, la transaction devient irr�versible.
</p><p class="p1">9.5. Si l'adresse e-mail du b�n�ficiaire n'est pas enregistr�e dans Erecovery, nous enverrons un e-mail de notification � cette adresse e-mail avec des instructions sur la mani�re de r�clamer et de recevoir le paiement. Si le b�n�ficiaire ne r�clame pas le paiement dans les quinze jours, les fonds vous seront restitu�s. Vous pouvez �galement annuler la transaction � tout moment si les fonds n'ont pas encore �t� cr�dit�s sur le compte Erecovery du b�n�ficiaire. Pour annuler une transaction, vous devez vous connecter � votre compte Erecovery, localiser la transaction appropri�e dans votre historique de transactions et choisir � Annuler �.
</p><p class="p1">9.6. Vous pouvez effectuer des paiements p�riodiques en cr�ant un ordre permanent sur votre compte. Vous pouvez annuler votre demande de paiement p�riodique pour des paiements futurs � tout moment en vous connectant � votre compte et en le supprimant. Vous ne pourrez pas annuler les transactions qui ont �t� d�j� cr�dit�es au b�n�ficiaire.
</p><p class="p1">9.7. Les paiements sont sujets � des limites de paiement pour des raisons de s�curit� et d�exigences l�gales. Ces limites sont fix�es dynamiquement selon votre statut de v�rification. Vous pouvez consulter ces limites � tout moment dans le profil de votre compte. Vous devez vous assurer que vos limites sont suffisantes pour couvrir le paiement que vous avez l'intention d'effectuer ainsi que tous les frais applicables, dont les frais de prestations de service et de conversion de devise. Vous devez garder � l�esprit que le b�n�ficiaire d'un paiement peut �galement �tre sujet � des limites de d�pense et de retrait et que cela peut influencer l'acc�s du b�n�ficiaire aux fonds que vous pr�voyez de lui envoyer.
</p><p class="p1">9.8. L'envoi des paiements est sujet � des frais et � des co�ts de conversion de devise en fonction du type de paiement que vous effectuez et du type de compte que vous avez. Veuillez consulter la section 14 pour de plus amples d�tails.
</p><p class="pTitle">10. R�ception de fonds
</p><p class="p1">10.1. Si vous recevez des fonds sur votre compte Erecovery, nous vous enverrons un e-mail de notification et afficherons le paiement comme transaction de r�ception d'argent dans votre historique de transactions. Vous devez r�guli�rement �tablir une correspondance entre les paiements entrants et vos propres archives.
</p><p class="p1">10.2. La confirmation de r�ception de paiements sur votre compte ne signifie pas n�cessairement que ces transactions ne sont pas annulables. Erecovery se r�serve le droit d'annuler un paiement au cas o� le d�biteur ou la banque du d�biteur ou le fournisseur de services de paiement a r�tro factur� ou annul� (ou est vraisemblablement susceptible de r�tro facturer ou d'annuler) un chargement ou tout autre paiement qui a �t� utilis� pour vous verser le paiement.
</p><p class="p1">10.3. Si une personne re�oit une notification de paiement d�Erecovery indiquant que quelqu'un lui a envoy� des fonds � une adresse e-mail qui n'est pas enregistr�e, elle ne sera pas cr�dit�e du paiement jusqu'� ce qu'elle le r�clame selon les instructions pr�sent�es dans l'e-mail de notification. Dans le cas contraire, il n'y aura aucun lien contractuel ni fiduciaire entre Erecovery et le b�n�ficiaire pr�vu. Les fonds restent ceux de l'exp�diteur.
</p><p class="p1">10.4. Vous pouvez r�clamer un paiement � quelqu'un en utilisant le service de � Demande de paiement � de votre compte. Vous ne devez utiliser ce service que pour des montants incontest�s qui sont dus en int�gralit� par une personne. Vous ne pouvez pas utiliser ce service plus d'une fois pour le m�me paiement que vous r�clamez. Ce service ne peut �tre utilis� comme outil de recouvrement de dettes ou de mesure contraignante. Si la personne qui vous doit un paiement vous demande de ne pas utiliser le service de � Demande de paiement � de Erecovery pour lui r�clamer le paiement, vous devez vous conformer � cette demande ind�pendamment du bien-fond� de votre r�clamation. En utilisant ce service, vous devez vous assurer que vous avez le droit de contacter la personne � laquelle vous r�clamez l'argent. Il vous est strictement interdit de r�clamer de l'argent � quelqu'un qui
<br>�    ne vous doit pas le montant demand� ;
<br>�    serait in�ligible pour ouvrir un compte Erecovery (par exemple, un mineur) ; ou
<br>�    n'a pas donn� ou a retir� son consentement pour recevoir une demande de paiement par l'interm�diaire du service de �Demande de paiement�;
<br> Et nous auront le droit de r�clamer une compensation pour tous les dommages ou pertes cons�cutifs � votre violation de cette interdiction.
</p><p class="p1">10.5. La r�ception des paiements est sujette � des frais divers et � des conversions de devise en fonction du type de paiement que vous recevez et du type de compte que vous avez. Veuillez consulter la section 14 pour de plus amples d�tails.
</p><p class="pTitle">11. Transactions interdites
</p><p class="p1">11.1. Il est strictement interdit d'envoyer ou de recevoir des paiements en compensation de la vente ou de la fourniture des articles suivants :
<br>�    Produits de tabac
<br>�    M�dicaments sous prescription
<br>�    Drogues et attirails associ�s � la consommation de drogues
<br>�    Armes � feu ou munitions
<br>�    Armes et couteaux
<br>�    D�sembrouiller de t�l�vision par satellite et par c�ble
<br>�    Pornographie
<br>�    Identifications et licences gouvernementales comprenant les reproductions et les originaux
<br>�    Loteries ou services de jeu non autoris�s
<br>�    Cartes de d�bit pr�pay�es ou autres cartes � valeur int�gr�e qui ne sont pas associ�es � un n�gociant particulier et ne sont pas limit�es aux achats de produits ou de services particuliers
<br>�    Marketing � plusieurs niveaux, vente pyramidale ou cha�ne de Ponzi, programmes matrices ou autre promotion du style � Devenez riche rapidement � ou plans d'investissement � rendement �lev�
<br>�    Biens ou services qui violent les droits de propri�t� intellectuelle d'un tiers.
<br>
Erecovery se r�serve le droit d'ajouter, � sa seule discr�tion, des cat�gories commerciales de transactions interdites en ajoutant de telles cat�gories aux pr�sentes conditions d'utilisation ou � une politique d'utilisation acceptable publi�e sur le site.
</p><p class="p1">11.2. Il est strictement interdit d'effectuer ou de recevoir des paiements en faveur ou provenant de personnes ou d'entit�s offrant des services de jeu, dont, entre autres, des paris sportifs, des jeux de casino et des parties de poker ill�gaux. Nous pouvons suspendre ou cl�turer votre compte Erecovery � tout moment ou refuser d'ex�cuter ou annuler une transaction si nous croyons que vous utilisez ou avons utilis� directement ou indirectement votre compte Erecovery pour des transactions de jeu ill�gales ou en rapport avec celles-ci. Il est de votre responsabilit� de vous assurer que vous n'utilisez pas nos services pour des transactions qui peuvent �tre consid�r�es comme ill�gales dans votre juridiction.
</p><p class="p1">11.3. Vous ne pouvez pas utiliser les services Erecovery si vous r�sidez dans l'un des pays suivants: Afghanistan, Cuba, Iran, Isra�l, Birmanie, Nig�ria, Cor�e du Nord, Somalie, Soudan ou Y�men. Cette liste n'est pas exhaustive et nous pouvons, � notre seule discr�tion, d�cider de cesser ou de limiter nos services dans d'autres pays � tout moment et sans pr�avis. Nous nous r�servons le droit de suspendre ou de cl�turer votre compte Erecovery � tout moment si nous estimons raisonnablement que la loi nous y oblige ou afin de nous conformer aux recommandations �mises par une autorit� gouvernementale comp�tente ou un corps reconnu pour la pr�vention des crimes financiers.
</p><p class="p1">11.4. Il est strictement interdit d'utiliser votre compte Erecovery � des fins ill�gales incluant, en autres, la fraude et le blanchiment d'argent. Erecovery signalera toute activit� suspecte � l'organisme comp�tent charg� de faire appliquer la loi. Il vous est interdit d'utiliser votre compte Erecovery pour essayer d'abuser, d'exploiter ou de contourner les restrictions d'utilisation impos�es par un marchand sur les services qu'il fournit.
</p><p class="p1">11.5. Vous ne pouvez accepter des paiements que pour certaines cat�gories d'affaires apr�s avoir re�u l'aval d�Erecovery � sa seule discr�tion. De telles cat�gories d'affaires incluent, sans y �tre limit�es :
<br>�    les entreprises d'�change ou de virement de fonds, incluant, mais sans y �tre limit�es, les bureaux de change, d��change de devises et d'achat d'argent de voyage;
<br>�    la collecte de toute forme de donations ou de paiements destin�s � des organismes caritatifs ou non lucratifs;
<br>�    le commerce de ressources naturelles telles que les bijoux, les pierres ou les m�taux pr�cieux ;
<br>�    la vente ou la fourniture de boissons alcoolis�es ; ou
<br>�    la vente ou la fourniture de compl�ments di�t�tiques et de produits de sant� alternatifs ;
<br>�    n'importe quelle autre cat�gorie d'affaires publi�e dans les activit�s interdits sur le site ;
<br>Au cas o� vous n�arriveriez pas � d�terminer si vos affaires tombent dans l'une ou l�autre de ces cat�gories, vous devez contacter le service client�le.
Erecovery se r�serve le droit d'ajouter, � seule discr�tion, des cat�gories commerciales exigeant une approbation en ajoutant de telles cat�gories aux pr�sentes conditions d'utilisation ou � une politique d'utilisation acceptable publi�e sur le site.
</p><p class="p1">11.6. Si vous menez ou essayez de mener toute transaction violant les interdictions contenues dans cette section 11 ou sans l'approbation n�cessaire comme mentionn�e � la section 11.5, nous nous r�servons le droit :
<br>�    d�annuler la transaction ; et/ou
<br>�    de fermer ou de suspendre votre compte ; et/ou
<br>�    de signaler la transaction � l'organisme comp�tent charg� de faire appliquer la loi ; et/ou
<br>�    de vous r�clamer des dommages ; et
<br>�    de vous imputer des frais de gestion jusqu'� 2500 DA au cas o� nous appliquerions l'une des mesures cit�es ci-dessus.</p>
<p class="p1">11.7. Il est de votre responsabilit� et non celle de Erecovery de vous assurer que vos paiements concernent uniquement des personnes ou des entit�s en compensation de la vente ou de la fourniture de biens et de services que vous avez le droit de fournir ou de recevoir conform�ment � toutes les lois et � tous les r�glements applicables. Le seul fait qu'une personne ou une entit� accepte des paiements via Erecovery n'est pas une indication de la l�galit� de la fourniture de ses biens ou de la prestation de des services. Si vous �tes dans le doute quant � la l�galit� d'une fourniture ou d'un achat, vous devez cesser votre paiement.
</p><p class="pTitle">12. Retrait de fonds
</p><p class="p1">12.1. Vous pouvez demander le retrait de l'ensemble ou d�une partie des fonds plac�s sur votre compte Erecovery � tout moment. Pour ce faire, vous devez vous connecter � votre compte, choisir un mode de retrait et saisir le montant � retirer. Les modes de retrait sont des services de paiement fournis, au moins en partie, par des institutions financi�res tierces (par exemple, la banque o� vous d�tenez un compte bancaire). Erecovery ne garantit la disponibilit� d'aucun mode de retrait particulier et peut rendre disponible, modifier ou cesser un mode de retrait particulier � tout moment sans suivre la proc�dure pr�sent�e dans la clause 18, tant qu'il y a au moins un mode de retrait � votre disposition. Si le paiement par retrait est re�u par vous par l'interm�diaire d'un fournisseur de services de paiement (tel que la banque o� vous d�tenez un compte bancaire), Erecovery ne sera plus responsable du paiement par retrait une fois que les fonds retir�s sont re�us par votre fournisseur de services de paiement.
</p><p class="p1">12.2. Votre compte est sujet � des limites de retrait. Ces limites sont ajust�es dynamiquement en fonction du type de document d'identit� que nous d�tenons vous concernant. Vous pouvez consulter vos limites de retrait � tout moment dans le profil de votre compte. Avant de charger quelque fonds que ce soit sur votre compte, vous devez vous assurer que vos limites de retrait et de d�pense actuelles r�pondent aux exigences de retrait et de d�pense qui vous sont impos�es car nous ne pouvons l�galement pas vous permettre de d�passer ces limites.
</p><p class="p1">12.3. Si votre demande de retrait d�passe la limite actuelle, nous pouvons refuser votre demande et, en revanche, vous demander de nous envoyer des documents confirmant votre identit� et votre adresse avant d�autoriser un retrait de fonds ou bien de coop�rer avec nous pour v�rifier votre identit�.
</p><p class="p1">12.4. Les retraits sont sujets aux frais de retrait et de conversion de devise en fonction du mode de retrait et de l'instrument de paiement choisis. Veuillez consulter la section 14 pour de plus amples d�tails.
</p><p class="p1">12.5. En ce qui concerne les transactions de retrait, Erecovery est un d�biteur et non pas un fournisseur de services de paiement.
</p><p class="p1">12.6. Vous ne devez pas effectuer de retrait au cr�dit d�un compte bancaire ni de tout autre instrument de paiement si vous n'�tes pas le d�tenteur d�sign�. Nous prenons toute violation de cette condition tr�s au s�rieux et traiterons n'importe quelle tentative d'utilisation d�un instrument de paiement dont vous n'�tes pas le d�tenteur d�sign� comme un acte frauduleux. Sous r�serve de tout droit de r�clamation de dommages ult�rieurs, si nous sommes contraints d�enqu�ter sur un chargement effectu� depuis un instrument de paiement qui n'est pas � votre nom, nous pouvons facturer des frais de gestion de 1000 DA.
</p><p class="p1">12.7. Vous devez vous assurer que les d�tails de paiement que vous saisissez lorsque vous retirez des fonds sont corrects et complets. Erecovery ne sera pas responsable des fonds retir�s et envoy�s � un instrument de paiement erron� s�il s�av�re que cette erreur est due aux d�tails de paiement incorrects que vous avez fournis. Lorsque vous effectuez un retrait au cr�dit d�un compte bancaire ou CCP, vous devez vous assurer que le num�ro de compte, le code guichet, le code RIB ou RIP sont corrects. Si vous avez retir� des fonds au cr�dit d�un instrument de paiement erron�, vous pouvez nous demander de vous aider � r�cup�rer les fonds ; cependant, nous vous facturerons des frais de gestion de 1500 DA pour ce service et nous ne pouvons pas garantir que ces efforts de r�cup�ration aboutiront.
</p><p class="pTitle">13. Service de d�p�t fiduciaire Erecovery
</p><p class="p1">13.1. Les paiements via Erecovery peuvent �tre sujets � notre service de d�p�t fiduciaire. Cela vous permet d'effectuer un paiement au cr�dit d�un b�n�ficiaire, sous r�serve de votre approbation de la transaction ult�rieurement.
</p><p class="p1">13.2. Le service de d�p�t fiduciaire est sujet aux conditions g�n�rales du service de d�p�t fiduciaire. Si vous optez pour un paiement par le service de d�p�t fiduciaire, vous acceptez d'�tre li�s par les conditions g�n�rales du service de d�p�t fiduciaire en plus des pr�sentes conditions d'utilisation.
</p><p class="pTitle">14. Frais
</p><p class="p1">14.1. Les frais varient si vous utilisez votre compte � des fins personnelles ou � des commerciales.
</p><p class="p1">14.2. Les frais li�s aux transactions peuvent �tre consult�s � tout moment dans la section Frais sur notre site. Des surtaxes s'appliquent aux comptes Erecovery utilis�s � des fins commerciales. Il est recommand� d�imprimer ou de t�l�charger une copie de la section � Frais � ainsi que des pr�sentes conditions d'utilisation et de les conserver. Les frais sont sujets � modification conform�ment � la section 18. Dans certaines circonstances, nous pouvons appliquer des frais suppl�mentaires, comme expliqu� dans les clauses 8.3, 8.8, 11.6, 12.6 et 12.7.
</p><p class="p1">14.3. Vos transactions peuvent �tre sujettes � des conversions de devise. Si vous achetez d'un fournisseur � l'�tranger conventionn� avec Erecovery.
</p><p class="p1">14.4. Pour chaque conversion de devise, Erecovery appliquera le taux de conversion indiqu� sur notre site. En outre, nous appliquerons des frais de devises �trang�res, qui sont �galement indiqu�s dans la section � Frais � du site et qui sont exprim�s en pourcentage applicable, en plus des frais de transaction.
</p><p class="p1">14.5. Nos frais sont soit exprim�s en pourcentage de la transaction soit en montant fixe en Dinar. Si des montants de frais fixes sont indiqu�s dans une devise autre que le Dinar, c'est � titre informatif uniquement. Si des frais sont d�duits d'un solde ou d'une transaction exprim�s dans une devise diff�rente, le montant des frais en Dinar sera converti en frais �quivalents dans cette autre devise, sur la base du taux de conversion applicable � ce moment-l�, et ensuite d�duit. Nous n'appliquerons pas de frais d��change de devises �trang�res sur des conversions de devise qui concernent des frais.
</p><p class="p1">14.6. Les frais payables par vous seront d�duits du solde de votre compte Erecovery. Des frais de transaction seront factur�s quand la transaction sera ex�cut�e. Si le solde de votre compte est insuffisant pour couvrir les frais, nous pouvons refuser d'ex�cuter le paiement. Des frais d'annulation ou de chargeback seront d�duits si encourus.
</p><p class="p1">14.7. Si la d�duction des frais a pour cons�quence un solde n�gatif sur votre compte, il vous sera demand� de rembourser ce solde n�gatif en chargeant des fonds suffisants sur votre compte Erecovery. Le manquement � cette demande est une infraction aux pr�sentes conditions d'utilisation. Le remboursement du solde n�gatif est d� imm�diatement sans communication pr�alable ; cependant, nous nous r�servons le droit � tout moment de vous envoyer les rappels dont vous avez besoin pour t�l�charger des fonds ou de prendre d'autres mesures de recouvrement de dettes, dont, entres autres, mandater une agence de recouvrement de dettes ou des avocats-conseils ou r�clamer l'indemnisation devant le tribunal. Nous nous r�servons le droit de vous facturer les d�penses que nous avons raisonnablement encourues dans le cadre d�un recouvrement de dettes ou de mesures contraignantes.
</p><p class="pTitle">15. Vos donn�es
</p><p class="p1">15.1. Le traitement de vos donn�es est r�gi par notre Politique en mati�re de protection de la vie priv�e, qui peut �galement �tre trouv�e sur notre site. En acceptant les pr�sentes conditions d�utilisation, vous �tes �galement d'accord sur les termes de notre politique en mati�re de protection de la vie priv�e. Il est recommand� d'imprimer et conserver une copie de notre politique en mati�re de protection de la vie priv�e ainsi que des pr�sentes conditions d'utilisation.
</p><p class="p1">15.2. Erecovery collecte, enregistre et traite vos donn�es conform�ment � la loi alg�rienne. Aucune donn�e n'est stock�e par nous en dehors de l'Alg�rie ou Canada; cependant, afin de vous fournir certains services frontaliers, nous pouvons �tre amen�s � partager vos donn�es avec des entit�s en dehors de l'Alg�rie. En effectuant des paiements en faveur ou en acceptant des paiements provenant de personnes ou d�entit�s en dehors de l'Alg�rie, vous consentez � ce que nous partagions vos donn�es avec des entit�s en dehors de l'Alg�rie dans la mesure o� cela est raisonnablement n�cessaire pour l'ex�cution appropri�e des paiements ou la prestation de nos services.
</p><p class="p1">15.3. Si vous d�tectez toute erreur dans les donn�es que nous d�tenons sur vous, vous devez corriger les donn�es dans le profil de votre compte ou, si ce n'est pas possible, en contactant le service client�le.
</p><p class="p1">15.4. Par d�faut, vous recevrez des newsletters par e-mail qui vous informeront sur les caract�ristiques des nouveaux produits, les �v�nements, les promotions, les offres sp�ciales, etc. En acceptant les pr�sentes conditions d�utilisation, vous acceptez de recevoir de telles newsletters par e-mail de fa�on r�guli�re. Si vous ne souhaitez pas recevoir de newsletter de notre part, vous pouvez choisir � tout moment de vous connecter � votre compte et de changer les param�tres appropri�s dans le profil de votre compte. Vous pouvez �galement cesser de recevoir des newsletters en contactant le service client�le. Chaque e-mail de newsletter que vous recevez vous donnera �galement la possibilit� de vous d�sinscrire pour les futures newsletters.
</p><p class="p1">15.5. Apr�s que la cl�ture de votre compte Erecovery pour quelque raison que ce soit, nous conserverons les donn�es de votre compte personnel pour une p�riode de cinq ans ou tout autre p�riode prescrite par la loi en vigueur.
</p><p class="pTitle">16. Responsabilit�
</p><p class="p1">16.1. En cas de paiement non autoris� ou d�un paiement qui a �t� ex�cut� erron�ment d� � une erreur d�Erecovery, Erecovery remboursera imm�diatement � votre demande le montant du paiement comprenant tous les frais d�duits de la somme en question. Ceci ne s'appliquera pas :
</p><p class="p1">16.1.1. Si le paiement non autoris� r�sulte de votre manquement � pr�server la s�ret� des caract�ristiques de s�curit� personnalis�es de votre compte conform�ment � la section 6 auquel cas vous resterez redevable des mille premiers dinars sauf si la clause 16.1.3 est d'application;
</p><p class="p1">16.1.2. Si vous ne nous informez pas promptement de la perte de votre mot de passe ou de tout autre �v�nement dont on pourrait raisonnablement s�attendre � ce qu�il compromette la s�curit� de votre compte apr�s avoir pris connaissance d'un tel �v�nement et vous resterez responsable des pertes encourues jusqu'au moment o� vous nous en informez ;
</p><p class="p1">16.1.3. S'il s�av�re que la transaction n��tait pas autoris�e et que vous avez compromis la s�curit� de votre compte Erecovery de fa�on intentionnelle ou par n�gligence grave, auquel cas vous serez tenu pour unique responsable de toutes pertes ; ou
</p><p class="p1">16.1.4. Si vous ne contestez pas et ne portez pas la transaction non autoris�e ou inexactement ex�cut�e � l�attention d�Erecovery dans les treize mois de la date de la transaction.
</p><p class="p1">16.2. La section 16.1.1 ne s'appliquera pas aux transactions effectu�es apr�s que vous nous avez mis au courant, conform�ment � la section 6.2, auquel cas Erecovery restera responsable et vous remboursera imm�diatement toute transaction non autoris�e.
</p><p class="p1">16.3. Sous r�serve de ce qui pr�c�de, vous �tes invit� � v�rifier l'historique de transactions de votre compte Erecovery r�guli�rement et fr�quemment et � contacter le service client�le imm�diatement pour toutes questions ou probl�mes.
</p><p class="p1">16.4. Dans le cas de paiements incorrects ou mal dirig�s, Erecovery prendra des mesures raisonnables pour vous aider � retrouver et � r�cup�rer ces paiements.
</p><p class="p1">16.5. Sous r�serve de ce qui pr�c�de, Erecovery ne sera tenu pour responsable d�aucune interruption ou perturbation de son service ni des interruptions ou des perturbations des services interm�diaires sur lesquels Erecovery se fonde pour le respect de ses engagements ci-dessous, � condition qu�une telle interruption ou perturbation soit due � des circonstances anormales et impr�vues ind�pendantes de son contr�le raisonnable ou du contr�le de l'interm�diaire concern�.
</p><p class="p1">16.6. Erecovery ne sera responsable d'aucunes pertes indirectes ou cons�cutives incluant, sans y �tre limit�es, le manque � gagner, la perte de clients et le ternissement de r�putation. Erecovery ne sera tenue responsable d'aucune perte r�sultant de notre respect de la loi et de r�glements de r�gulation.
</p><p class="p1">16.7. Rien dans les pr�sentes conditions d'utilisation n�est pr�vu pour exclure la responsabilit� en cas de mort ou de dommage corporel caus�s par n�gligence ou en cas de fraude, de d�claration frauduleuse ou de n'importe quelle responsabilit� statutaire qui ne peut pas �tre exclue ou modifi�e par un accord entre les parties.
</p><p class="p1">16.8. L�engagement de Erecovery en vertu des pr�sentes conditions d'utilisation se limite � vous fournir un compte Erecovery et des services de paiement connexes et ne commente ni ne cautionne la qualit�, la s�curit� ou la l�galit� des biens ou des services fournis par un client de Erecovery.
</p><p class="p1">16.9. Erecovery ne sera responsable de l'estimation ou du paiement d'aucun imp�t, d�aucune taxe ni d�aucune autre charge r�sultant de la transaction commerciale initiale entre vous et un autre client de Erecovery.
</p><p class="pTitle">17. Cl�ture et suspension
</p><p class="p1">17.1. Nous pouvons cl�turer votre compte Erecovery ou n'importe quel service de paiement li� � celui-ci sans vous donnant de pr�avis. Vous pouvez cl�turer votre compte � tout moment. Diff�rents droits de cl�ture peuvent s'appliquer selon les termes d'un accord marchand si vous d�tenez un compte de n�gociant.
</p><p class="p1">17.2. En m�me temps qu'une notification de cl�ture ou � tout moment par la suite, nous pouvons vous donner des instructions raisonnables sur la fa�on dont vous pouvez retirer les fonds restants.
</p><p class="p1">17.3. Si votre compte est sujet � une r�serve, la cl�ture de votre compte n'alt�rera pas notre droit de garder la r�serve et d�y faire les d�ductions n�cessaires pour la p�riode convenue.
</p><p class="p1">17.4. Nous pouvons � tout moment suspendre ou cl�turer votre compte Erecovery sans communication pr�alable :
</p><p class="p1">17.4.1. Si vous contrevenez � l�une des clauses des pr�sentes conditions d'utilisation ou � tout autre clause applicable aux services sp�cifiques couverts par des conditions g�n�rales s�par�es ;
</p><p class="p1">17.4.2. Si vous violez ou si nous avons des raisons de croire que vous �tes en infraction � toute loi ou � tout r�glement qui s'applique � votre utilisation des services Erecovery ; ou
</p><p class="p1">17.4.3. Si nous avons des raisons de croire que vous �tes de quelque fa�on que ce soit impliqu� dans toute activit� frauduleuse, de blanchiment d'argent, de financement d�actes terroristes ou toute autre activit� criminelle.
</p><p class="p1">17.5. Nous pouvons suspendre votre compte � tout moment :
</p><p class="p1">17.5.1. Si nous croyons raisonnablement que votre compte a �t� compromis ou pour d'autres raisons de s�curit� ; ou
</p><p class="p1">17.5.2. Si nous suspectons raisonnablement que votre compte a �t� utilis� ou est utilis� sans votre autorisation ou frauduleusement ; en outre, nous vous informerons soit avant la suspension soit, si le pr�avis n'est pas possible vu les circonstances, promptement apr�s la suspension � moins que nous en soyons interdits l�galement.
</p><p class="pTitle">18. Modifications des pr�sentes conditions d'utilisation
</p><p class="p1">18.1. Les pr�sentes conditions d'utilisation et toutes les conditions g�n�rales additionnelles qui peuvent s'appliquer aux services compl�mentaires sont sujettes � modification. Les modifications seront mises en application avec notification pr�alable d�Erecovery selon la proc�dure d�termin�e dans la pr�sente section.
</p><p class="p1">18.2. Erecovery vous notifiera de toute modification propos�e en envoyant un e-mail � l'adresse principale enregistr�e dans votre compte.
</p><p class="p1">18.3. La modification propos�e entrera en vigueur deux mois apr�s la date de la notification de modification, � moins que vous nous ayez notifi� que vous vous opposez aux modifications propos�es avant que celles-ci n�entrent en vigueur. Les modifications qui rendent les pr�sentes conditions d'utilisation plus favorables pour vous entreront en vigueur imm�diatement, pour autant que cela soit indiqu� dans la notification de modification. Les modifications des taux de change entreront en vigueur imm�diatement sans communication pr�alable et vous n'aurez pas le droit de vous opposer � de telles modifications.
</p><p class="p1">18.4. Si vous vous opposez aux modifications, elles ne s'appliqueront pas � vous ; cependant, une telle objection de votre part constituera une notification de fin et de cl�ture de votre compte.
</p><p class="pTitle">19. Notre mode de communication
</p><p class="p1">19.1. Nous communiquons habituellement avec vous par e-mail. � cet effet, vous devez � tout moment avoir au moins une adresse e-mail valable dans le profil de votre compte. Vous �tes tenu de v�rifier les messages entrants r�guli�rement et fr�quemment. Les e-mails peuvent contenir des liens vers des communications ult�rieures sur notre site.
</p><p class="p1">19.2. Si la l�gislation exige que nous vous fournissions des informations sur un support durable, nous vous enverrons un e-mail (avec ou sans pi�ce jointe) ou nous vous enverrons une notification vous renvoyant � des informations sur notre site d'une mani�re qui vous permettra de conserver les informations dans un format d'impression ou dans un autre format qui peut �tre conserv� par vous de mani�re permanente pour r�f�rence future. Vous �tes tenu de conserver des copies de toutes les communications que nous vous envoyons ou que nous mettons � votre disposition.
</p><p class="p1">19.3. Vous pouvez demander une copie des conditions d'utilisation actuelles ou de n'importe quel autre document contractuel vous concernant en contactant le service client�le.
</p><p class="p1">19.4. Afin de consulter vos e-mails, vous avez besoin d'un ordinateur avec un logiciel d'e-mail qui peut afficher des e-mails au format HTML. Nous pouvons �galement vous envoyer des pi�ces jointes au format PDF (Portable Document Format d�Adobe Systems Inc.), pour lequel vous avez besoin du logiciel Acrobat Reader d'Adobe, qui peut �tre t�l�charg� gratuitement sur www.adobe.com.
</p><p class="p1">19.5. Nous ne vous enverrons jamais aucun e-mail avec des fichiers ex�cutables en pi�ce jointe ou avec des liens renvoyant � des fichiers ex�cutables. Si vous recevez un e-mail avec de telles pi�ces jointes, vous devez supprimer le message sans cliquer sur la pi�ce jointe. Si vous n��tes pas s�r qu�une communication vienne de nous, contactez notre service client�le.
</p><p class="p1">19.6. Nous communiquerons avec vous en Arabe ou Fran�ais et accepterons toujours des communications � notre attention en arabe ou fran�ais. Vous pouvez choisir votre langue pr�f�r�e dans la liste des langues prises en charge dans le profil de votre compte et nous vous enverrons des notifications et des communications par e-mail automatis� concernant les modifications apport�es aux pr�sentes conditions d'utilisation dans la langue de votre choix. Pour les communications non standard, nous nous r�servons le droit de communiquer avec vous en arabe ou en fran�ais. Les documents ou les communications peuvent �tre transmis dans d�autres langues � des fins pratiques uniquement et ne constitueront pas une obligation de notre part de continuer � communiquer dans cette langue.
</p><p class="p1">19.7. Ind�pendamment de la communication par e-mail, nous pouvons vous contacter par lettre ou par t�l�phone, le cas �ch�ant. Si vous utilisez des services mobiles, nous pouvons communiquer avec vous par SMS.
</p><p class="p1">19.8. Vous pouvez nous contacter � tout moment en envoyant un message au service client�le via le service � Contacter nous � sur notre site ou en appelant au +213 21 77 0202,  +213 21 77 0303.
</p><p class="pTitle">20. Plaintes
</p><p class="p1">20.1. Toutes les plaintes concernant Erecovery ou les services que nous fournissons doivent nous �tre adress�es en premier lieu par le biais du service client�le. Vous devez clairement indiquer que vous souhaitez d�poser une plainte contre nous. Cela nous aide � distinguer une plainte d'une simple question. Nous accuserons r�ception des plaintes dans les cinq jours ouvrables. Vous pouvez demander � recevoir une copie de notre proc�dure de plaintes � tout moment.
</p><p class="p1">20.2. Nous faisons en sorte de fournir une r�ponse ou une r�solution � votre plainte dans des d�lais raisonnables. Si ce n'est pas possible d� � des circonstances impr�vues ou � un manque d'informations, nous vous contacterons.
</p><p class="pTitle">21. Divers
</p><p class="p1">21.1. Les pr�sentes conditions d'utilisation ne conf�rent aucun droit � une autre personne que vous.
</p><p class="p1">21.2. Votre compte Erecovery vous est personnel et vous ne pouvez attribuer aucun droit � aucun tiers en vertu des conditions d'utilisation.
</p><p class="p1">21.3. Votre compte Erecovery est g�r� � Alger et les pr�sentes conditions d'utilisation seront r�gies par et interpr�t�es selon les lois d'Alg�rie. Tout litige en vertu des pr�sentes conditions d'utilisation ou bien en rapport avec votre compte Erecovery sera port� exclusivement devant la cour d'Alger.
</p>
<p class="pTitle">22. D�finitions</p>
<p class="p1">
Les diverses clauses des pr�sentes conditions d'utilisation ont une signification bien d�finie ; vous trouverez les diff�rentes d�finitions ci-apr�s :
�Service client�le� : le service client�le d�Erecovery, que vous pouvez joindre en envoyant un message via le service � Contact � sur le site ou en appelant au <?php echo $data['ContactNumber']?></p>
</p>
<br>
<BR>
    
        </div>
    </article>
    <div class="clr"></div>

</div>

<!-- End content  -->

